-- ═══════════════════════════════════════════════════════════════
-- Step 6: receta schema tables
-- Must come BEFORE mes.partida_paso and mes.lavado_maquina
-- which have FK → receta.tenido and receta.lavado_maquina.
--
-- NOTE: receta.tenido uses articulo_tipo_id + fibra (not a specific articulo_id).
--       A recipe applies to all fabric variants of the same type + fiber composition.
--       Both crear_tenido() and generar_receta() key off articulo_tipo_id + fibra.
-- FIX (BUG 4): removed stray "SELECT * FROM paso" query.
-- ═══════════════════════════════════════════════════════════════

-- ── estado_desarrollo_color ───────────────────────────────────
DROP TABLE IF EXISTS estado_desarrollo_color CASCADE;
CREATE TABLE IF NOT EXISTS estado_desarrollo_color (
    id     SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre TEXT     NOT NULL,
    codigo TEXT     NOT NULL UNIQUE
);
INSERT INTO estado_desarrollo_color (nombre, codigo) VALUES
    ('Ingresado',          'INGRESADO'),
    ('En Desarrollo',      'EN_DESARROLLO'),
    ('Enviado al Cliente', 'ENVIADO_CLIENTE'),
    ('Aprobado',           'APROBADO'),
    ('Rechazado',          'RECHAZADO'),
    ('Cancelado',          'CANCELADO'),
    ('Re Lab',             'RE_LAB'),
    ('Histórico',          'HISTORICO')
ON CONFLICT (codigo) DO NOTHING;

-- Migration: if estado_desarrollo_color already exists without codigo column:
-- ALTER TABLE estado_desarrollo_color ADD COLUMN IF NOT EXISTS codigo TEXT;
-- UPDATE estado_desarrollo_color SET codigo = CASE nombre
--     WHEN 'Ingresado' THEN 'INGRESADO' WHEN 'En Desarrollo' THEN 'EN_DESARROLLO'
--     WHEN 'Enviado al Cliente' THEN 'ENVIADO_CLIENTE' WHEN 'Aprobado' THEN 'APROBADO'
--     WHEN 'Rechazado' THEN 'RECHAZADO' WHEN 'Cancelado' THEN 'CANCELADO'
--     WHEN 'Re Lab' THEN 'RE_LAB' END WHERE codigo IS NULL;
-- INSERT INTO estado_desarrollo_color (nombre, codigo) VALUES ('Histórico', 'HISTORICO') ON CONFLICT DO NOTHING;

-- ── receta.operacion ──────────────────────────────────────────
CREATE TABLE receta.operacion (
    id           SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo       TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL UNIQUE,
    nombre       TEXT NOT NULL
);
CREATE TRIGGER trg_bi_receta_operacion_codigo_canon
BEFORE INSERT OR UPDATE ON receta.operacion
FOR EACH ROW
EXECUTE FUNCTION fn_trg_set_codigo_canon();

INSERT INTO receta.operacion (codigo, nombre) VALUES
    ('TINTURA',          'Tintura'),
    ('LAVADO',           'Lavado'),
    ('LAVADO_REDUCTIVO', 'Lavado Reductivo'),
    ('BLANQUEO_QUIMICO', 'Blanqueo Químico'),
    ('BLANQUEO_OPTICO',  'Blanqueo Óptico'),
    ('DESCRUDE',         'Descrude'),
    ('NEUTRALIZADO',     'Neutralizado'),
    ('SUAVIZADO',        'Suavizado'),
    ('FIJADO',           'Fijado'),
    ('JABONADO',         'Jabonado'),
    ('ENJUAGUE',         'Enjuague'),
    ('MATIZADO',         'Matizado'),
    ('ANTIPILLING',      'Antipilling'),
    ('REGULACION_PH',    'Regulación de pH'),
    ('SIMULTANEO',       'Simultáneo'),
    ('DESMONTADO',       'Desmontado'),
    ('REBAJE',           'Rebaje')
ON CONFLICT (codigo) DO NOTHING;

-- ── receta.tenido ──────────────────────────────────────────────
-- articulo_tipo_id + fibra: recipe is defined at article-type/fiber level,
-- not per specific articulo (color variant). Multiple articulos of the same
-- type and fiber share the same recipe.
CREATE TABLE receta.tenido (
    id                 INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color_x_cliente_id INT      REFERENCES color_x_cliente(id),
    articulo_tipo_id   SMALLINT REFERENCES articulo_tipo(id),
    fibra              SMALLINT,
    tenido_id          INT      REFERENCES tenido(id),
    flg_antipilling    BOOLEAN  NOT NULL DEFAULT false,
    tipo_receta_id     SMALLINT NOT NULL REFERENCES tipo_receta(id),
    estado_id          SMALLINT NOT NULL REFERENCES estado_desarrollo_color(id),
    flg_produccion     BOOLEAN  NOT NULL DEFAULT false,
    fyh_produccion     TIMESTAMPTZ,
    usr_cre            INT      REFERENCES usuario(id),
    fyh_cre            TIMESTAMPTZ DEFAULT now(),
    usr_mod            INT      REFERENCES usuario(id),
    fyh_mod            TIMESTAMPTZ
);

CREATE OR REPLACE FUNCTION fn_trg_receta_tenido_flg_produccion()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_aprobado_id SMALLINT;
BEGIN
    SELECT id INTO v_aprobado_id FROM estado_desarrollo_color WHERE codigo = 'APROBADO';
    NEW.flg_produccion := (NEW.estado_id = v_aprobado_id);
    RETURN NEW;
END;$$;

CREATE TRIGGER trg_bi_receta_tenido_flg_produccion
BEFORE INSERT OR UPDATE OF estado_id ON receta.tenido
FOR EACH ROW EXECUTE FUNCTION fn_trg_receta_tenido_flg_produccion();

CREATE UNIQUE INDEX uq_receta_tenido_aprobada
    ON receta.tenido(color_x_cliente_id, articulo_tipo_id, fibra, tenido_id, flg_antipilling)
    WHERE flg_produccion = true;

-- ── receta.tenido_paso ────────────────────────────────────────
CREATE TABLE receta.tenido_paso (
    id           INT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_id    INT      NOT NULL REFERENCES receta.tenido(id),
    operacion_id SMALLINT NOT NULL REFERENCES receta.operacion(id),
    orden        SMALLINT NOT NULL,
    ph           NUMERIC(4,2),
    temperatura  NUMERIC(5,2),
    tiempo_min   SMALLINT,
    nota         TEXT,
    UNIQUE(receta_id, orden)
);

-- ── receta.tenido_paso_insumo ─────────────────────────────────
CREATE TABLE receta.tenido_paso_insumo (
    id       INT            GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    paso_id  INT            NOT NULL REFERENCES receta.tenido_paso(id) ON DELETE CASCADE,
    item_id  INT            NOT NULL REFERENCES item(id),
    cantidad NUMERIC(10,6)  NOT NULL,  -- 10,6: max 9999.999999 (NUMERIC(8,6) would limit integer part to 99)
    medida   TEXT           NOT NULL DEFAULT 'g_kg' CHECK (medida IN ('g_kg', 'pct')),
    orden    SMALLINT       NOT NULL,
    UNIQUE(paso_id, orden)
);

-- ── receta.tenido immutability ───────────────────────────────
-- Prevent modifying a dyeing recipe once it has completed production executions.
-- Estado/audit cols remain writable (lifecycle transitions must still be possible).
-- Same pattern as receta.lavado_maquina below.
-- NOTE: references mes.partida_paso/ejecucion defined in 07_... — resolved at runtime.

CREATE OR REPLACE FUNCTION receta.fn_trg_tenido_immutable()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM mes.partida_paso pp
        JOIN mes.partida_paso_ejecucion pe ON pe.partida_paso_id = pp.id
        WHERE pp.receta_id = OLD.id
          AND pe.estado = 'COMPLETADO'
    ) THEN
        RAISE EXCEPTION
            'receta.tenido id=% cannot be modified: it has completed production executions',
            OLD.id;
    END IF;
    RETURN NEW;
END;
$$;

-- Guard identity fields only; estado_id/audit cols remain writable.
-- flg_antipilling is excluded: it is derived by trigger from tenido_paso operacion presence.
CREATE TRIGGER trg_bu_tenido_immutable
BEFORE UPDATE OF color_x_cliente_id, articulo_tipo_id, fibra, tenido_id, tipo_receta_id
ON receta.tenido
FOR EACH ROW EXECUTE FUNCTION receta.fn_trg_tenido_immutable();

CREATE OR REPLACE FUNCTION receta.fn_trg_tenido_paso_immutable()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_receta_id INT := COALESCE(OLD.receta_id, NEW.receta_id);
BEGIN
    IF EXISTS (
        SELECT 1
        FROM mes.partida_paso pp
        JOIN mes.partida_paso_ejecucion pe ON pe.partida_paso_id = pp.id
        WHERE pp.receta_id = v_receta_id
          AND pe.estado = 'COMPLETADO'
    ) THEN
        RAISE EXCEPTION
            'receta.tenido_paso id=% cannot be modified: its recipe has completed executions',
            OLD.id;
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$;

CREATE TRIGGER trg_bud_tenido_paso_immutable
BEFORE UPDATE OF operacion_id, orden, ph, temperatura, tiempo_min
ON receta.tenido_paso
FOR EACH ROW EXECUTE FUNCTION receta.fn_trg_tenido_paso_immutable();

CREATE TRIGGER trg_bd_tenido_paso_immutable
BEFORE DELETE ON receta.tenido_paso
FOR EACH ROW EXECUTE FUNCTION receta.fn_trg_tenido_paso_immutable();

CREATE OR REPLACE FUNCTION receta.fn_trg_tenido_paso_insumo_immutable()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_receta_id INT;
BEGIN
    SELECT tp.receta_id INTO v_receta_id
    FROM receta.tenido_paso tp
    WHERE tp.id = COALESCE(OLD.paso_id, NEW.paso_id);

    IF EXISTS (
        SELECT 1
        FROM mes.partida_paso pp
        JOIN mes.partida_paso_ejecucion pe ON pe.partida_paso_id = pp.id
        WHERE pp.receta_id = v_receta_id
          AND pe.estado = 'COMPLETADO'
    ) THEN
        RAISE EXCEPTION
            'receta.tenido_paso_insumo id=% cannot be modified: its recipe has completed executions',
            OLD.id;
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$;

CREATE TRIGGER trg_bud_tenido_paso_insumo_immutable
BEFORE UPDATE OF item_id, cantidad, medida, orden
ON receta.tenido_paso_insumo
FOR EACH ROW EXECUTE FUNCTION receta.fn_trg_tenido_paso_insumo_immutable();

CREATE TRIGGER trg_bd_tenido_paso_insumo_immutable
BEFORE DELETE ON receta.tenido_paso_insumo
FOR EACH ROW EXECUTE FUNCTION receta.fn_trg_tenido_paso_insumo_immutable();


-- ── receta.lavado_maquina ─────────────────────────────────────
-- FIX (BUG 4): removed stray "SELECT * FROM paso" that was between these tables.
CREATE TABLE receta.lavado_maquina (
    id                INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_lavado_mq_id SMALLINT REFERENCES tipo_lavado_maquina(id),
    valor_origen_id   SMALLINT REFERENCES valor(id),
    valor_destino_id  SMALLINT REFERENCES valor(id),
    flg_activo        BOOLEAN  DEFAULT true,
    usr_cre           INT      REFERENCES usuario(id),
    fyh_cre           TIMESTAMPTZ DEFAULT now(),
    usr_mod           INT      REFERENCES usuario(id),
    fyh_mod           TIMESTAMPTZ
);

-- Only one active recipe per (machine type, from-value, to-value) transition.
CREATE UNIQUE INDEX uq_receta_lavado_maquina_activa
    ON receta.lavado_maquina(tipo_lavado_mq_id, valor_origen_id, valor_destino_id)
    WHERE flg_activo = true;

-- Prevent editing a recipe that has already been executed.
CREATE OR REPLACE FUNCTION receta.fn_trg_lavado_maquina_immutable()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM mes.lavado_maquina
        WHERE receta_id = OLD.id AND estado = 'COMPLETADO'
    ) THEN
        RAISE EXCEPTION
            'receta.lavado_maquina id=% cannot be modified: it has completed executions',
            OLD.id;
    END IF;
    RETURN NEW;
END;
$$;

-- Only guard the three definition fields; flg_activo / audit cols can still be updated
-- even when the recipe has completed executions (activate/deactivate remains possible).
CREATE TRIGGER trg_bu_lavado_maquina_immutable
BEFORE UPDATE OF tipo_lavado_mq_id, valor_origen_id, valor_destino_id ON receta.lavado_maquina
FOR EACH ROW EXECUTE FUNCTION receta.fn_trg_lavado_maquina_immutable();

-- ── receta.lavado_maquina_paso ────────────────────────────────
CREATE TABLE receta.lavado_maquina_paso (
    id           INT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_id    INT      NOT NULL REFERENCES receta.lavado_maquina(id),
    operacion_id SMALLINT NOT NULL REFERENCES receta.operacion(id),
    orden        SMALLINT NOT NULL,
    ph           NUMERIC(4,2),
    temperatura  NUMERIC(5,2),
    tiempo_min   SMALLINT,
    nota         TEXT,
    UNIQUE(receta_id, orden)
);

-- ── receta.lavado_maquina_paso_insumo ─────────────────────────
CREATE TABLE receta.lavado_maquina_paso_insumo (
    id       INT            GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    paso_id  INT            NOT NULL REFERENCES receta.lavado_maquina_paso(id) ON DELETE CASCADE,
    item_id  INT            NOT NULL REFERENCES item(id),
    cantidad NUMERIC(10,6)  NOT NULL,  -- 10,6: max 9999.999999
    orden    SMALLINT       NOT NULL,
    UNIQUE(paso_id, orden)
);

-- ── Grants ────────────────────────────────────────────────────
GRANT SELECT ON estado_desarrollo_color              TO authenticated;
GRANT USAGE ON SCHEMA receta                         TO authenticated;
GRANT SELECT ON receta.operacion                     TO authenticated;
GRANT SELECT ON receta.tenido                        TO authenticated;
GRANT SELECT ON receta.tenido_paso                   TO authenticated;
GRANT SELECT ON receta.tenido_paso_insumo            TO authenticated;
GRANT SELECT ON receta.lavado_maquina                TO authenticated;
GRANT SELECT ON receta.lavado_maquina_paso           TO authenticated;
GRANT SELECT ON receta.lavado_maquina_paso_insumo    TO authenticated;
