-- ═══════════════════════════════════════════════════════════════
-- Step 7: doc, mes, calidad tables
-- Depends on: Step 5 (foundation), Step 6 (receta)
-- Key FK chains:
--   mes.partida → cliente, prioridad, tenido, color_x_cliente (all legacy)
--   mes.partida → mes.partida
--   mes.partida_paso → receta.tenido
--   mes.lavado_maquina → receta.lavado_maquina
--   calidad.inspeccion → inventario.lote, mes.partida_paso_ejecucion
-- ═══════════════════════════════════════════════════════════════

-- ── mes.partida ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mes.partida (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    numero int GENERATED BY DEFAULT AS IDENTITY,
    partida_origen_id bigint REFERENCES mes.partida(id),  -- for reprocessing/rework: link to original order
    prioridad_id int REFERENCES prioridad(id),
    tercero_id INT NOT NULL REFERENCES tercero(id),
    tenido_id int NOT NULL REFERENCES tenido(id),
    color_x_cliente_id int NOT NULL REFERENCES color_x_cliente(id),
    articulo_tipo_id SMALLINT NOT NULL REFERENCES articulo_tipo(id),  -- fabric type for this batch (billing key); restricts assignable rolls
    fibra            SMALLINT NOT NULL,                                -- fiber count; with articulo_tipo_id forms the recipe lookup key
    malla text,
    rendimiento text,
    ancho text,
    flg_antipilling boolean NOT NULL DEFAULT false,
    flg_doble_bolsa boolean NOT NULL DEFAULT false,
    fecha_acordada date,                           -- agreed delivery date with client (SAP: EDATU)
    observacion text,
    estado_produccion partida_estado_produccion_enum NOT NULL DEFAULT 'CREADA',
    -- Billing axis — orthogonal to production state.
    -- Updated when doc.factura lines are issued against this order.
    estado_comercial partida_estado_comercial_enum NOT NULL DEFAULT 'PENDIENTE',
    estado_facturacion partida_facturacion_enum NOT NULL DEFAULT 'pendiente',
    -- Price snapshot — "the price given" for this partida (per-kg rate only; no amounts/IGV/totals).
    -- NULL = derive from doc.catalogo_precios at dispatch date (default, the catalog is the source).
    -- non-NULL = override: a negotiated price, OR a frozen value immutable to later catalog edits.
    -- See migration/patches/26_partida_precio_kg.sql. Added 2026-06-17.
    precio_kg           NUMERIC(10,4) CHECK (precio_kg IS NULL OR precio_kg >= 0),
    CONSTRAINT chk_rework_comercial_locked
        CHECK (partida_origen_id IS NULL OR estado_comercial = 'PENDIENTE'),
    fyh_programacion timestamptz,
    fyh_inicio timestamptz,
    fyh_fin timestamptz,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    usr_elm INT,
    fyh_elm TIMESTAMPTZ
);

-- SAP AFPO equivalent: planned output item per production order.
-- cantidad          = planned roll count (AFPO.GAMNG)
-- cantidad_producida = confirmed yield, incremented by registrar_produccion (AFPO.WEMNG)
-- kg breakdown is NOT stored here — derived from item_movimientos PROD_ING rows.
CREATE TABLE IF NOT EXISTS mes.partida_detalle (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    partida_id bigint NOT NULL REFERENCES mes.partida(id),
    item_id int NOT NULL REFERENCES item(id),
    cantidad           numeric(12,2) NOT NULL CHECK (cantidad > 0),
    cantidad_producida numeric(12,2) NOT NULL DEFAULT 0,
    unidad_id int NOT NULL REFERENCES unidad(id),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE (partida_id, item_id)
);

-- ── doc.guia_remision_tipo ────────────────────────────────────
CREATE TABLE IF NOT EXISTS doc.guia_remision_tipo (
    id  smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    nombre text,
    flg_emitida boolean NOT NULL,
    flg_cliente boolean,
    item_movimiento_tipo_id SMALLINT REFERENCES inventario.item_movimiento_tipo(id),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE(codigo_canon)
);
CREATE TRIGGER trg_bi_guia_remision_tipo_codigo_canon
BEFORE INSERT OR UPDATE ON doc.guia_remision_tipo
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

INSERT INTO doc.guia_remision_tipo (codigo, nombre, flg_emitida, flg_cliente) VALUES
    ('COMPRA_INGRESO',            'Compra – Ingreso de insumos',                       false, false),
    ('VENTA_EGRESO',              'Venta – Egreso de producto terminado',               true,  true),
    ('CLIENTE_ENVIO_PROCESO',     'Servicio – Recepción de material cliente',           false, true),
    ('DESPACHO_CLIENTE',          'Servicio – Despacho de material procesado a cliente',true,  true),
    ('DEVOLUCION_CLIENTE_CRUDO',  'Devolución a cliente (rollos sin procesar)',         true,  true),
    ('DEVOLUCION_PROVEEDOR',      'Devolución a proveedor',                            true,  false);

UPDATE doc.guia_remision_tipo grt
SET item_movimiento_tipo_id = imt.id
FROM inventario.item_movimiento_tipo imt
WHERE
    (grt.codigo = 'COMPRA_INGRESO'           AND imt.codigo = 'COMPRA_ING')
 OR (grt.codigo = 'VENTA_EGRESO'             AND imt.codigo = 'VENTA_EGR')
 OR (grt.codigo = 'CLIENTE_ENVIO_PROCESO'    AND imt.codigo = 'SERV_ING')
 OR (grt.codigo = 'DESPACHO_CLIENTE'         AND imt.codigo = 'SERV_EGR')
 OR (grt.codigo = 'DEVOLUCION_CLIENTE_CRUDO' AND imt.codigo = 'DEV_CLI_EGR')
 OR (grt.codigo = 'DEVOLUCION_PROVEEDOR'     AND imt.codigo = 'DEV_PROV_EGR');

INSERT INTO doc.guia_remision_tipo (codigo, nombre, flg_emitida, flg_cliente, item_movimiento_tipo_id)
SELECT 'DEVOLUCION_CLIENTE_VENTA', 'Devolución de cliente (producto vendido)', false, true, imt.id
FROM inventario.item_movimiento_tipo imt WHERE imt.codigo = 'DEV_CLI_ING';

INSERT INTO doc.guia_remision_tipo (codigo, nombre, flg_emitida, flg_cliente, item_movimiento_tipo_id)
SELECT 'DEVOLUCION_CLIENTE_SERVICIO', 'Devolución de cliente (material de servicio)', false, true, imt.id
FROM inventario.item_movimiento_tipo imt WHERE imt.codigo = 'SERV_DEV_ING';

-- ── doc.guia_remision ─────────────────────────────────────────
-- Acts as the delivery document for both inbound and outbound movements.
-- serie/correlativo are nullable: headless records represent movement events
-- where the legal document is handled externally (e.g. dispatch via separate system)
-- or not yet registered. Both must be provided together or not at all.
CREATE TABLE IF NOT EXISTS doc.guia_remision (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    guia_remision_tipo_id smallint NOT NULL REFERENCES doc.guia_remision_tipo(id),
    tercero_id  INT NOT NULL REFERENCES tercero(id),  -- the external party; direction derived from guia_remision_tipo.flg_emitida
    serie TEXT,
    correlativo TEXT,
    fecha_emision TIMESTAMPTZ NOT NULL,
    fecha_recepcion TIMESTAMPTZ DEFAULT now(),
    usr_cre int,
    fyh_cre timestamptz DEFAULT NOW(),
    usr_mod int,
    fyh_mod timestamptz,
    usr_elm INT,
    fyh_elm TIMESTAMPTZ,
    CONSTRAINT chk_guia_doc_fields CHECK ((serie IS NULL) = (correlativo IS NULL)),
    UNIQUE (tercero_id, serie, correlativo, guia_remision_tipo_id)
);

-- ── doc.guia_remision_detalle ─────────────────────────────────
-- One row per physical guia line (linea = line number on the paper/PDF).
-- n_rollos: roll count declared on the guia line (separate from cantidad which is weight).
-- lote_id: populated for dispatch guias (identifies exact rolls going out);
--          populated after ingress for inbound guias; NULL before lot creation.
-- ubicacion_id: warehouse bin context when relevant.
CREATE TABLE IF NOT EXISTS doc.guia_remision_detalle (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    guia_remision_id BIGINT NOT NULL REFERENCES doc.guia_remision(id),
    linea SMALLINT NOT NULL DEFAULT 1,
    item_id INT NOT NULL REFERENCES item(id),
    lote_id int REFERENCES inventario.lote(id),
    ubicacion_id int REFERENCES inventario.ubicacion(id),
    cantidad NUMERIC(12,4) NOT NULL CHECK (cantidad > 0),
    n_rollos INT,
    UNIQUE (guia_remision_id, linea)
);

-- ── doc.orden_servicio ───────────────────────────────────────
-- Commercial service order issued by admin for MLR's manufacturing arm
-- to have rolls dyed at the plant. Serves as the ingress anchor for
-- internally-confectioned rolls (parallel to guia_remision for external clients).
-- Physical paper number stored in serie/correlativo; the PDF is just evidence.
-- Lotes created against this order carry orden_servicio_id on lote_rollo_detalle.
-- Added via migration/22_orden_servicio.sql.
CREATE TABLE IF NOT EXISTS doc.orden_servicio (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tercero_id      INT         NOT NULL REFERENCES tercero(id),
    serie           TEXT        NOT NULL,
    correlativo     INT         NOT NULL,
    fecha_emision   DATE        NOT NULL DEFAULT CURRENT_DATE,
    fecha_entrega   DATE,
    rendimiento     TEXT,
    ancho           TEXT,
    flg_antipilling BOOLEAN     NOT NULL DEFAULT false,
    flg_urgente     BOOLEAN     NOT NULL DEFAULT false,
    observacion     TEXT,
    factura         TEXT,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ,
    flg_elm BOOLEAN NOT NULL DEFAULT false,
    usr_elm INT,  fyh_elm TIMESTAMPTZ,
    UNIQUE (tercero_id, serie, correlativo)
);

CREATE TRIGGER trg_biud_orden_servicio_audit
    BEFORE INSERT OR UPDATE OR DELETE ON doc.orden_servicio
    FOR EACH ROW EXECUTE FUNCTION audit.fn_audit_row();
CREATE TRIGGER trg_bi_orden_servicio_audit
    BEFORE INSERT ON doc.orden_servicio
    FOR EACH ROW EXECUTE FUNCTION public.fn_trg_set_cre_fields();
CREATE TRIGGER trg_bu_orden_servicio_audit
    BEFORE UPDATE ON doc.orden_servicio
    FOR EACH ROW EXECUTE FUNCTION public.fn_trg_set_mod_fields();

-- ── doc.orden_servicio_detalle ────────────────────────────────
-- Intent lines: what was ordered. cantidad = roll count.
-- color_x_cliente_id + tenido_id are known at order time (NOT NULL).
CREATE TABLE IF NOT EXISTS doc.orden_servicio_detalle (
    id                  BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    orden_servicio_id   BIGINT      NOT NULL REFERENCES doc.orden_servicio(id),
    linea               SMALLINT    NOT NULL,
    item_id             INT         NOT NULL REFERENCES item(id),
    -- articulo_id removed: derivable via item_rollo_detalle.articulo_id
    malla               TEXT,
    cantidad            INT         NOT NULL CHECK (cantidad > 0),   -- ordered roll count (intent)
    cantidad_recibida   INT         NOT NULL DEFAULT 0,              -- received so far; bumped by ingresar_orden_servicio
    color_x_cliente_id  INT         NOT NULL REFERENCES color_x_cliente(id),
    tenido_id           INT         NOT NULL REFERENCES tenido(id),
    flg_doble_bolsa     BOOLEAN     NOT NULL DEFAULT false,
    UNIQUE (orden_servicio_id, linea)
);

CREATE TRIGGER trg_biud_orden_servicio_detalle_audit
    BEFORE INSERT OR UPDATE OR DELETE ON doc.orden_servicio_detalle
    FOR EACH ROW EXECUTE FUNCTION audit.fn_audit_row();

-- ── inventario.pesaje ─────────────────────────────────────────
-- Placed here (after mes.partida) so the table ordering is clear,
-- though pesaje no longer holds FKs to any mes table.
-- → Defined after mes.partida below.

-- ── mes.operacion ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mes.operacion (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    nombre text NOT NULL,
    requiere_receta boolean DEFAULT false,
    requiere_maquina boolean DEFAULT true,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE (nombre),
    UNIQUE (codigo_canon)
);
CREATE TRIGGER trg_bi_operacion_codigo_canon
BEFORE INSERT OR UPDATE ON mes.operacion
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

INSERT INTO mes.operacion (codigo, nombre, requiere_receta) VALUES
    ('TERMOFIJADO',  'Termofijado',  false),
    ('TENIDO',       'Teñido',       true),
    ('LAVADO_HIDRO', 'Lavado Hidro', true),
    ('SECADO',       'Secado',       false),
    ('PLANCHADO',    'Planchado',    false),
    ('PERCHADO',     'Perchado',     false),
    ('COMPACTADO',   'Compactado',   false),
    ('VOLTEADO',     'Volteado',     false)
ON CONFLICT (codigo) DO NOTHING;

-- ── mes.maquina_tipo ──────────────────────────────────────────
CREATE TABLE mes.maquina_tipo (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    nombre text,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE(codigo_canon),
    UNIQUE(nombre)
);
CREATE TRIGGER trg_bi_maquina_tipo_codigo_canon
BEFORE INSERT OR UPDATE ON mes.maquina_tipo
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

-- ── mes.maquina ───────────────────────────────────────────────
CREATE TABLE mes.maquina (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    nombre text NOT NULL,
    maquina_tipo_id smallint REFERENCES mes.maquina_tipo(id),
    estado_actual maquina_estado_enum NOT NULL DEFAULT 'espera',
    ultimo_mantenimiento timestamptz,
    horas_totales int,
    capacidad_min_kg int NOT NULL CHECK (capacidad_min_kg > 0),
    capacidad_max_kg int NOT NULL CHECK (capacidad_max_kg >= capacidad_min_kg),
    relacion_bano numeric(5,2),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    usr_elm int,
    fyh_elm TIMESTAMPTZ,
    UNIQUE(codigo_canon)
);
CREATE TRIGGER trg_bi_maquina_codigo_canon
BEFORE INSERT OR UPDATE ON mes.maquina
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

DROP TRIGGER IF EXISTS trg_bi_gen_codigo_maquina ON mes.maquina;
CREATE TRIGGER trg_bi_gen_codigo_maquina
BEFORE INSERT ON mes.maquina
FOR EACH ROW EXECUTE FUNCTION mes.fn_trg_gen_codigo_maquina();

-- ── mes.empleado_rol ──────────────────────────────────────────
CREATE TABLE mes.empleado_rol (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    nombre text NOT NULL,
    descripcion text,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE(codigo_canon)
);
CREATE TRIGGER trg_bi_empleado_rol_codigo_canon
BEFORE INSERT OR UPDATE ON mes.empleado_rol
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

-- ── mes.empleado ──────────────────────────────────────────────
CREATE TABLE mes.empleado (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre text,
    apellido text,
    rol_id smallint NOT NULL REFERENCES mes.empleado_rol(id),
    turno_id smallint REFERENCES turno(id),   -- legacy FK
    activo   BOOLEAN NOT NULL DEFAULT true,
    perfil_id INT REFERENCES public.usuario(id),  -- auth user account link for employee portal
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ
);

-- ── mes.ruta_plantilla ────────────────────────────────────────
CREATE TABLE mes.ruta_plantilla (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    usr_elm int,
    fyh_elm timestamptz
);

CREATE TABLE mes.ruta_plantilla_detalle (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ruta_plantilla_id int NOT NULL REFERENCES mes.ruta_plantilla(id),
    operacion_id smallint NOT NULL REFERENCES mes.operacion(id),
    secuencia smallint NOT NULL,
    ph numeric(4,2),
    temperatura numeric(5,2),
    tiempo_estandar int,
    UNIQUE (ruta_plantilla_id, secuencia)
);

-- ── mes.partida_paso ─────────────────────────────────────────
-- AFVC equivalent: planned steps for a job.
-- Planning intent only: maquina_planificada_id, receta_id, target params.
-- Execution state (who ran it, when, actual params) lives in partida_paso_ejecucion.
-- Completion is derived: a paso is done when it has a COMPLETADO partida_paso_ejecucion row.
CREATE TABLE mes.partida_paso (
    id                      bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    partida_id              bigint NOT NULL REFERENCES mes.partida(id),
    secuencia               smallint NOT NULL,
    operacion_id            smallint NOT NULL REFERENCES mes.operacion(id),
    maquina_planificada_id  int REFERENCES mes.maquina(id),
    receta_id               int REFERENCES receta.tenido(id),
    tiempo_estandar         int,
    ph_objetivo             numeric(4,2),
    temperatura_objetivo    numeric(5,2),
    relacion_bano_objetivo  numeric(5,2),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE (partida_id, secuencia)
);

-- ── mes.programacion ─────────────────────────────────────────
-- actividad_tipo = 'partida_paso'  → actividad_id is mes.partida_paso.id
--   (schedule links to the PLANNED step; the execution run is created when the step starts)
-- actividad_tipo = 'LAVADO_MAQUINA' → actividad_id is mes.lavado_maquina.id
CREATE TABLE mes.programacion (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actividad_tipo TEXT NOT NULL,
    actividad_id   BIGINT NOT NULL,
    maquina_id int NOT NULL REFERENCES mes.maquina(id),
    fecha date NOT NULL,
    secuencia smallint NOT NULL,
    nota text,
    usr_cre int,
    fyh_cre timestamptz DEFAULT now(),
    usr_mod int,
    fyh_mod timestamptz,
    UNIQUE (maquina_id, fecha, secuencia),
    CONSTRAINT chk_programacion_actividad_tipo
        CHECK (actividad_tipo IN ('partida_paso', 'LAVADO_MAQUINA'))
);

-- ── mes.partida_paso_ejecucion ────────────────────────────────
-- AFRU equivalent: actual execution run of a planned step.
-- One partida_paso can have 1..N partida_paso_ejecucion rows (normal run + lagging continuations).
-- A run is created when it starts — no PENDIENTE state.
-- Yield (production output lotes) is posted by registrar_produccion when finalizing the run
-- that generates output (typically the TENIDO step). No schema flag marks this — the
-- caller submits a produccion payload only for the appropriate step.
-- documento reference: inventario.lote and item_movimientos use
--   documento_tipo = 'partida_paso_ejecucion', documento_id = this row's id.
CREATE TABLE mes.partida_paso_ejecucion (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    partida_paso_id bigint NOT NULL REFERENCES mes.partida_paso(id),
    estado          paso_ejecucion_estado_enum NOT NULL DEFAULT 'EN_PROCESO',
    maquina_id      int REFERENCES mes.maquina(id),
    empleado_id     smallint REFERENCES mes.empleado(id),
    fyh_inicio      timestamptz NOT NULL DEFAULT now(),
    fyh_fin         timestamptz,
    ph_real             numeric(4,2),
    temperatura_real    numeric(5,2),
    relacion_bano_real  numeric(5,2),
    cantidad_rollos     numeric(12,4),  -- roll count confirmed in this run (snapshot; ≈ SAP AFRU yield in pieces)
    peso_kg             numeric(12,4),  -- weight processed (snapshot): output lote sum (final step) or prorated input (non-final). Immune to reproceso splits.
    cantidad_scrap      numeric(12,4),  -- rolls condemned mid-execution (≈ SAP AFRU.AFRUASC)
    notas           text,
    programacion_id BIGINT REFERENCES mes.programacion(id),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ
);

-- ── mes.partida_componente ────────────────────────────────────
-- Unified reservation table (≈ SAP RESB) covering all components of a partida:
--   Roll rows:     lote_id IS NOT NULL, item_id IS NULL,  partida_paso_id IS NULL
--                  Assigned at order level via actualizar_componentes_partida.
--   Chemical rows: item_id IS NOT NULL, lote_id IS NULL,  partida_paso_id IS NOT NULL
--                  Populated by generar_receta when a recipe step is applied.
--                  cantidad_reservada = recipe qty scaled to actual batch weight.
--                  Serves as the expected consumption baseline for variance alerts.
CREATE TABLE mes.partida_componente (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    partida_id          bigint NOT NULL REFERENCES mes.partida(id),
    lote_id             int             REFERENCES inventario.lote(id),
    item_id             int             REFERENCES item(id),
    partida_paso_id     bigint          REFERENCES mes.partida_paso(id) ON DELETE CASCADE,
    cantidad_reservada  numeric(15,7),  -- 7 dp: kg = grams÷1000, preserves 4 gram-decimals (see generar_receta)
    usr_cre int,
    fyh_cre timestamptz DEFAULT now(),
    usr_mod int,
    fyh_mod timestamptz,
    CONSTRAINT chk_resb_tipo CHECK (
        (lote_id IS NOT NULL AND item_id IS NULL  AND partida_paso_id IS NULL)
        OR
        (item_id IS NOT NULL AND lote_id IS NULL  AND partida_paso_id IS NOT NULL)
    )
);
-- One roll per order
CREATE UNIQUE INDEX uq_resb_roll    ON mes.partida_componente(partida_id, lote_id)       WHERE lote_id IS NOT NULL;
-- One chemical reservation per step per item
CREATE UNIQUE INDEX uq_resb_insumo  ON mes.partida_componente(partida_paso_id, item_id)  WHERE item_id IS NOT NULL;

-- ── inventario.pesaje ─────────────────────────────────────────
-- One row per lote. tipo discriminates when/why the weight was recorded:
--   'INGRESO'    — roll weighed at receival (primary flow, registrar_pesaje_produccion)
--   'CORRECCION' — post-assignment weight fix (rare, corregir_pesaje_produccion / actualizar_pesos_individuales_partida)
--   'SALIDA'     — output roll weighed at production time (registrar_produccion)
-- Context is derivable via item_movimientos but tipo avoids the join for simple checks.
CREATE TABLE inventario.pesaje (
    id          INT  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    lote_id     INT  NOT NULL REFERENCES inventario.lote(id),
    tipo        TEXT NOT NULL CHECK (tipo IN ('INGRESO', 'SALIDA', 'CORRECCION')),
    peso_real   NUMERIC(12,4),
    observacion TEXT,
    usr_cre     INT,
    fyh_cre     TIMESTAMPTZ DEFAULT NOW()
);

-- ── inventario.lote_rollo_detalle ────────────────────────────
-- SAP Batch Classification equivalent for roll lotes.
-- 1:1 extension of inventario.lote for ROLLO lotes.
-- Every ROLLO lote must have exactly one row here (enforced at all creation points).
--
--   item             → stable catalog (what material it is)
--   lote             → physical instance (this specific roll)
--   lote_rollo_detalle → processing state (what has been done to it)
--
-- Attributes set at ingress: guia_remision_id (billing anchor)
-- Physical attributes (ancho, malla, rendimiento): set from partida at production time
-- Dyeing attributes: color_x_cliente_id, tenido_id, flg_tenido, flg_antipilling
--   set when dyeing step completes (registrar_produccion)
-- origen_lote_id: SAP parent-batch pattern — output lote → input lote.
--   NULL for original input lotes (no parent).
--   Set by registrar_produccion. Enables O(1) billing weight lookup:
--   source_lote.cantidad = pre-production input weight (authoritative for billing).
--
-- Replaces lote.detalles JSONB for roll-specific attributes.
CREATE TABLE inventario.lote_rollo_detalle (
    lote_id             INT PRIMARY KEY REFERENCES inventario.lote(id),

    -- Billing anchor — set at ingress, carried forward through production
    guia_remision_id    BIGINT REFERENCES doc.guia_remision(id),

    -- Parent-batch link: output lote → input lote it was produced from.
    -- NULL for original input lotes. Set by registrar_produccion.
    origen_lote_id      INT REFERENCES inventario.lote(id),

    -- Physical attributes — set at ingress (from partida) or on first weighing
    ancho               TEXT,
    malla               TEXT,
    rendimiento         TEXT,

    -- Thread (hilo) supplier invoice this roll was spun from. Free-text bridge
    -- field for orden_servicio (MLR-confectioned) rolls — the seam where the
    -- unmapped confection process hands off to dyeing. Set at ingress from the
    -- OS line's value, fanned to every roll on the line. Supersede with real
    -- thread-lot genealogy if/when manufacturing is modeled. NOT an FK.
    factura_hilo        TEXT,

    -- Dyeing identity — set when production (dyeing) step completes
    color_x_cliente_id  INT REFERENCES color_x_cliente(id),
    tenido_id           INT REFERENCES tenido(id),
    flg_tenido          BOOLEAN NOT NULL DEFAULT false,
    flg_antipilling     BOOLEAN NOT NULL DEFAULT false,

    usr_cre INT,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT,
    fyh_mod TIMESTAMPTZ
);

-- ── mes.lavado_maquina ────────────────────────────────────────
CREATE TABLE mes.lavado_maquina (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_id   INT NOT NULL REFERENCES receta.lavado_maquina(id),
    maquina_id  INT NOT NULL REFERENCES mes.maquina(id),
    estado      partida_paso_estado_enum NOT NULL DEFAULT 'PENDIENTE',
    empleado_id SMALLINT REFERENCES mes.empleado(id),
    fyh_inicio  TIMESTAMPTZ,
    fyh_fin     TIMESTAMPTZ,
    nota        TEXT,
    usr_cre     INT,
    fyh_cre     TIMESTAMPTZ DEFAULT NOW(),
    usr_mod     INT,
    fyh_mod     TIMESTAMPTZ
);

-- ── calidad ───────────────────────────────────────────────────
CREATE TABLE calidad.inspeccion (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    lote_id int NOT NULL REFERENCES inventario.lote(id),
    partida_paso_ejecucion_id bigint REFERENCES mes.partida_paso_ejecucion(id),
    resultado calidad_estado_enum NOT NULL,
    observacion text,
    empleado_id int REFERENCES mes.empleado(id),
    fyh_inspeccion timestamptz DEFAULT now(),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE calidad.tipo_defecto (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    UNIQUE (codigo_canon),
    nombre text NOT NULL,
    descripcion text,
    severidad smallint DEFAULT 1,
    activo boolean DEFAULT true
);
CREATE TRIGGER trg_bi_tipo_defecto_codigo_canon
BEFORE INSERT OR UPDATE ON calidad.tipo_defecto
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

INSERT INTO calidad.tipo_defecto (codigo, nombre, descripcion, severidad) VALUES
('LINEA',            'Línea / Raya',                  'Línea visible en sentido de urdimbre o trama',               2),
('MANCHA',           'Mancha',                        'Mancha de aceite, óxido, suciedad u otro agente',            2),
('HUECO',            'Hueco',                         'Perforación o rotura en la tela',                            3),
('HILO_ROTO',        'Hilo roto',                     'Filamento o hilo cortado visible en la superficie',          2),
('CAIDA_MALLA',      'Caída de malla',                'Malla suelta o partida en tejido de punto',                  3),
('HILO_GRUESO',      'Hilo grueso / delgado',         'Variación de título de hilo visible',                        1),
('CONTAMINACION',    'Contaminación / Fibra extraña', 'Fibra o material ajeno atrapado en el tejido',              2),
('TONO_DESIGUAL',    'Tono desigual',                 'Variación de tono dentro del mismo rollo',                   2),
('BARRADO',          'Barrado',                       'Franjas horizontales por diferencia de tensión o lote',      3),
('PILLING',          'Pilling',                       'Bolitas de fibra en la superficie',                          1),
('PESO_FUERA_SPEC',  'Peso fuera de especificación',  'Gramaje (g/m²) fuera de tolerancia',                        2),
('ANCHO_FUERA_SPEC', 'Ancho fuera de especificación', 'Ancho del rollo fuera de tolerancia',                       2),
('ENCOGIMIENTO',     'Encogimiento excesivo',         'Encogimiento superior al permitido tras lavado/partida',     3),
('ARRUGA',           'Arruga / Quiebre',              'Marca de pliegue permanente',                                1),
('ORILLO_DEFECTUOSO','Orillo defectuoso',             'Orillo enrollado, cortado o irregular',                      1);

CREATE TABLE calidad.inspeccion_defecto (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inspeccion_id bigint NOT NULL REFERENCES calidad.inspeccion(id),
    tipo_defecto_id smallint NOT NULL REFERENCES calidad.tipo_defecto(id),
    cantidad smallint DEFAULT 1,
    observacion text
);

CREATE TABLE calidad.inspeccion_foto (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inspeccion_defecto_id bigint NOT NULL REFERENCES calidad.inspeccion_defecto(id),
    ruta_archivo text NOT NULL,
    etiqueta text,
    observacion text,
    usr_cre int,
    fyh_cre timestamptz DEFAULT now()
);

-- ── doc.factura_proveedor ─────────────────────────────────────
CREATE TABLE doc.factura_proveedor (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tercero_id   INT NOT NULL REFERENCES tercero(id),
    serie       TEXT NOT NULL,
    numero      INT  NOT NULL,
    fecha_emision       DATE NOT NULL,
    fecha_vencimiento   DATE,
    tipo_pago   tipo_pago_enum NOT NULL DEFAULT 'al contado',
    moneda      CHAR(3) NOT NULL DEFAULT 'USD',
    tipo_cambio NUMERIC(10,4),
    subtotal    NUMERIC(12,2) NOT NULL DEFAULT 0,
    igv         NUMERIC(12,2) NOT NULL DEFAULT 0,
    total       NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado_pago estado_pago_enum NOT NULL DEFAULT 'pendiente',
    observacion TEXT,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ,
    UNIQUE (tercero_id, serie, numero),
    CONSTRAINT chk_factura_montos CHECK (
        subtotal > 0 AND igv >= 0 AND total > 0
        AND ABS(total - (subtotal + igv)) < 0.01
    )
);

-- ── doc.factura_proveedor_detalle ─────────────────────────────
-- Per-line detail of a supplier invoice.
-- Authoritative source for item purchase price — use this for
-- recipe cost calculations, not compra_detalle.precio_unitario.
-- compra_detalle.precio_unitario is the estimated/agreed price at the
-- time of purchase registration (which may precede the invoice).
-- A factura_proveedor without detalle rows is valid for lump-sum invoices.
CREATE TABLE doc.factura_proveedor_detalle (
    id                   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    factura_proveedor_id BIGINT        NOT NULL REFERENCES doc.factura_proveedor(id),
    item_id              INT           NOT NULL REFERENCES item(id),
    cantidad             NUMERIC(12,4) NOT NULL CHECK (cantidad > 0),
    precio_unitario      NUMERIC(12,4) NOT NULL CHECK (precio_unitario >= 0),
    igv_porcentaje       NUMERIC(5,2)  NOT NULL DEFAULT 18
                             CHECK (igv_porcentaje IN (0, 18)),
    subtotal_linea       NUMERIC(12,2) GENERATED ALWAYS AS
                             (ROUND(cantidad * precio_unitario, 2)) STORED,
    igv_linea            NUMERIC(12,2) GENERATED ALWAYS AS
                             (ROUND(cantidad * precio_unitario * igv_porcentaje / 100, 2)) STORED,
    total_linea          NUMERIC(12,2) GENERATED ALWAYS AS
                             (ROUND(cantidad * precio_unitario * (1 + igv_porcentaje / 100), 2)) STORED,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE doc.compra (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tercero_id  INT NOT NULL REFERENCES tercero(id),
    fecha       DATE NOT NULL DEFAULT CURRENT_DATE,
    observacion TEXT,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ,
    usr_elm INT,  fyh_elm TIMESTAMPTZ
);

-- ── doc.compra_factura_proveedor ───────────────────────────────
-- N:M junction: one compra can be covered by multiple invoices
-- (e.g. partial shipments, amended invoices, factura-en-0 + real).
-- One factura can consolidate multiple compras from the same supplier.
CREATE TABLE doc.compra_factura_proveedor (
    compra_id            BIGINT NOT NULL REFERENCES doc.compra(id),
    factura_proveedor_id BIGINT NOT NULL REFERENCES doc.factura_proveedor(id),
    PRIMARY KEY (compra_id, factura_proveedor_id),
    usr_cre  INT,
    fyh_cre  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE doc.compra_detalle (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    compra_id       BIGINT NOT NULL REFERENCES doc.compra(id),
    item_id         INT    NOT NULL REFERENCES item(id),
    cantidad        NUMERIC(12,4) NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12,4) NOT NULL CHECK (precio_unitario >= 0),
    -- Denormalized from ledger (≈ SAP EKPO.WEMNG).
    -- Maintained by compras.sql after every guia link or unlink.
    cantidad_recibida  NUMERIC(12,4) NOT NULL DEFAULT 0,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE doc.compra_guia_remision (
    compra_id        BIGINT NOT NULL REFERENCES doc.compra(id),
    guia_remision_id BIGINT NOT NULL REFERENCES doc.guia_remision(id),
    PRIMARY KEY (compra_id, guia_remision_id)
);

-- ── doc.catalogo_precios ──────────────────────────────────────
-- Per-kg rate for each billable service combination.
-- All prices are in USD — MLR bills exclusively in USD.
--
-- Lookup key: operacion × color/client × article type × dyeing × fiber.
-- NULL in any dimension = wildcard (matches any value of that dimension).
-- Most-specific active match wins — see doc.fn_get_precio().
--
-- Historicity: rows are immutable once created. To change a price,
-- set fyh_elm on the current row (via doc.upsert_catalogo_precio)
-- and insert a new row. This preserves pricing history for invoice
-- reconstruction without a separate history table.
--
-- Antipilling — two separate concerns, two separate rows:
--   1. TENIDO rows carry flg_antipilling=false/true to track costo_kg per recipe variant.
--      Both variants may share the same precio_kg (negotiated at base level) but differ
--      in costo_kg because the antipilling recipe uses different/more chemicals.
--   2. ANTIPILLING ghost operation row (client-level wildcard, tercero_id only):
--      the service charge billed as a second invoice line when partida.flg_antipilling=true.
--      Rate: 0.15/kg Urban, 0.10/kg others (maintained via upsert_catalogo_precio).
--
-- costo_kg: chemical cost per kg snapshot at time of price-setting (ex-IGV).
-- NULL for legacy rows and non-dyeing operations.
-- Margin is always derived: (precio_kg - costo_kg) / precio_kg.
--
-- tercero_id: client-level wildcard dimension.
-- Specificity tiers (high → low):
--   color_x_cliente_id  — specific color for specific client
--   tercero_id          — any color for this client
--   both NULL           — universal default
-- color_x_cliente_id and tercero_id are mutually exclusive.
CREATE TABLE IF NOT EXISTS doc.catalogo_precios (
    id                  BIGINT   GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Lookup dimensions (NULL = wildcard)
    -- flg_antipilling: distinguishes base recipe cost from antipilling variant cost on TENIDO rows.
    --   NULL = wildcard (applies to both). Only set when recipe cost differs (TENIDO op).
    --   ANTIPILLING operation rows always have flg_antipilling = NULL.
    operacion_id        SMALLINT NOT NULL REFERENCES mes.operacion(id),
    color_x_cliente_id  INT      REFERENCES color_x_cliente(id),
    tercero_id          INT      REFERENCES tercero(id),
    articulo_tipo_id    SMALLINT REFERENCES articulo_tipo(id),
    tenido_id           INT      REFERENCES tenido(id),
    fibra               SMALLINT,
    flg_antipilling     BOOLEAN,

    -- Prices (USD/kg)
    precio_kg           NUMERIC(10,4) NOT NULL CHECK (precio_kg >= 0),

    -- Cost snapshot (ex-IGV, from recipe at time of price-setting)
    costo_kg            NUMERIC(10,4)           CHECK (costo_kg IS NULL OR costo_kg >= 0),

    -- Audit (fyh_elm = inactive: superseded or deleted)
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_elm INT, fyh_elm TIMESTAMPTZ,

    CONSTRAINT chk_precio_client_dim
        CHECK (color_x_cliente_id IS NULL OR tercero_id IS NULL)
);

GRANT SELECT, INSERT, UPDATE ON doc.catalogo_precios TO authenticated;


-- ── doc.articulo_tipo_familia ─────────────────────────────────
-- Commercial PRICING families: maps each articulo_tipo to the bucket whose
-- catalogo_precios row applies (the legacy normalization, now as editable data).
--   tercero_id IS NULL → default family for all clients
--   tercero_id = <id>  → per-client override (flat-rate clients → family 20)
-- Resolved by doc.fn_familia_precio (funciones/facturacion.sql), used for the
-- TENIDO price lookup only — recipes match the LITERAL articulo_tipo.
-- Seeded + existing catalog rows re-pointed in
-- migration/patches/25_articulo_tipo_familia.sql.
CREATE TABLE IF NOT EXISTS doc.articulo_tipo_familia (
    articulo_tipo_id SMALLINT NOT NULL REFERENCES articulo_tipo(id),
    tercero_id       INT               REFERENCES tercero(id),  -- NULL = default for all clients
    familia_id       SMALLINT NOT NULL REFERENCES articulo_tipo(id),
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ
);
-- One default per type (tercero_id NULL), one override per (type, client).
CREATE UNIQUE INDEX IF NOT EXISTS uq_articulo_tipo_familia_default
    ON doc.articulo_tipo_familia(articulo_tipo_id) WHERE tercero_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_articulo_tipo_familia_cliente
    ON doc.articulo_tipo_familia(articulo_tipo_id, tercero_id) WHERE tercero_id IS NOT NULL;

GRANT SELECT ON doc.articulo_tipo_familia TO authenticated;



-- ── doc.letra ─────────────────────────────────────────────────
-- Payment instrument (SAP: payment document).
-- Standalone — not tied to a single factura.
-- Clearing to one or more facturas is done via doc.letra_factura.
-- tercero_id: the provider who issued the letra.
CREATE TABLE doc.letra (
    id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tercero_id        INT  NOT NULL REFERENCES tercero(id),
    numero            TEXT,
    monto             NUMERIC(12,2) NOT NULL CHECK (monto > 0),
    fecha_giro        DATE,
    fecha_vencimiento DATE NOT NULL,
    banco             TEXT,
    estado            letra_estado_enum NOT NULL DEFAULT 'emitida',
    fecha_pago        DATE,
    observacion       TEXT,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ
);

-- ── doc.letra_factura ─────────────────────────────────────────
-- Clearing document: applies a portion of a letra to a factura_proveedor.
-- SAP equivalent: clearing item / open item matching.
-- One letra → N facturas; one factura → N letras (many-to-many with amount).
-- monto_aplicado: portion of letra.monto allocated to this factura.
-- Invariant (enforced by registrar_letra): SUM(monto_aplicado) per letra ≤ letra.monto
CREATE TABLE doc.letra_factura (
    id                   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    letra_id             BIGINT NOT NULL REFERENCES doc.letra(id),
    factura_proveedor_id BIGINT NOT NULL REFERENCES doc.factura_proveedor(id),
    monto_aplicado       NUMERIC(12,2) NOT NULL CHECK (monto_aplicado > 0),
    UNIQUE (letra_id, factura_proveedor_id),
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW()
);

-- ── doc.factura ───────────────────────────────────────────────
-- Emitted customer invoices (facturas de venta / boletas).
-- Financial closure document for one or more partidas.
-- SUNAT FE integration: push to Siigo API (or similar) after estado = 'emitida'.
--
-- tipo_comprobante codes follow SUNAT standard:
--   '01' = Factura        (RUC buyer, full tax credit)
--   '03' = Boleta de Venta (DNI/RUC buyer, no credit)
--   '07' = Nota de Crédito
--   '08' = Nota de Débito
CREATE TABLE doc.factura (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo_comprobante    CHAR(2) NOT NULL DEFAULT '01'
                            CHECK (tipo_comprobante IN ('01','03','07','08')),
    serie               TEXT NOT NULL,          -- e.g. F001, B001, T001
    numero              INT  NOT NULL,          -- correlative
    tercero_id          INT  NOT NULL REFERENCES tercero(id),
    fecha_emision       DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_vencimiento   DATE,
    moneda              CHAR(3) NOT NULL DEFAULT 'USD',
    tipo_cambio         NUMERIC(10,4),          -- only relevant when moneda = 'USD'
    subtotal            NUMERIC(12,2) NOT NULL DEFAULT 0,
    igv                 NUMERIC(12,2) NOT NULL DEFAULT 0,   -- 18 % standard rate
    total               NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado              factura_estado_enum NOT NULL DEFAULT 'borrador',
    -- Nota de crédito/débito linkage (nullable — only set for 07/08 types)
    factura_origen_id   BIGINT REFERENCES doc.factura(id),
    observacion         TEXT,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ,
    usr_elm INT, fyh_elm TIMESTAMPTZ,
    UNIQUE (serie, numero),
    CONSTRAINT chk_factura_montos CHECK (
        subtotal >= 0 AND igv >= 0 AND total >= 0
        AND ABS(total - (subtotal + igv)) < 0.01
    ),
    CONSTRAINT chk_nota_requiere_origen CHECK (
        tipo_comprobante NOT IN ('07','08') OR factura_origen_id IS NOT NULL
    )
);

-- ── doc.factura_detalle ────────────────────────────────────────
-- One row per (ingress guia × operacion × billing dimensions).
-- partida_id links back to the sales order for billing-to-order reconciliation.
-- igv_porcentaje allows 0% for IGV-exempt items (e.g. exported goods).
--
-- guia_remision_id: ingress guia (CLIENTE_ENVIO_PROCESO) — the material-origin
--   anchor the client recognizes on their invoice. Carried forward from the input
--   lote via lote_rollo_detalle.guia_remision_id when registrar_produccion runs.
--   NULL for ad-hoc lines or MLR-confectioned rolls without an ingress guia.
-- operacion_id: which billable service (TENIDO, PLANCHADO...). NULL for ad-hoc.
-- es_antipilling: true for the antipilling surcharge line on TENIDO.
-- Billing dimensions denormalized at invoice time — financial document is
-- self-contained and does not depend on partida state.
CREATE TABLE doc.factura_detalle (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    factura_id          BIGINT NOT NULL REFERENCES doc.factura(id),
    -- Sales order line this invoice line covers (nullable for ad-hoc lines)
    partida_id          BIGINT   REFERENCES mes.partida(id),
    -- Billing document links (denormalized at invoice time)
    guia_remision_id    BIGINT   REFERENCES doc.guia_remision(id),
    operacion_id        SMALLINT REFERENCES mes.operacion(id),
    es_antipilling      BOOLEAN  NOT NULL DEFAULT false,
    articulo_tipo_id    SMALLINT REFERENCES articulo_tipo(id),
    color_x_cliente_id  INT      REFERENCES color_x_cliente(id),
    tenido_id           INT      REFERENCES tenido(id),
    descripcion         TEXT   NOT NULL,
    cantidad            NUMERIC(12,4) NOT NULL CHECK (cantidad > 0),
    unidad_id           INT    NOT NULL REFERENCES unidad(id),
    precio_unitario     NUMERIC(12,4) NOT NULL CHECK (precio_unitario >= 0),
    igv_porcentaje      NUMERIC(5,2)  NOT NULL DEFAULT 18
                            CHECK (igv_porcentaje IN (0, 18)),
    -- Stored computed columns avoid rounding drift across lines
    subtotal_linea      NUMERIC(12,2) GENERATED ALWAYS AS
                            (ROUND(cantidad * precio_unitario, 2)) STORED,
    igv_linea           NUMERIC(12,2) GENERATED ALWAYS AS
                            (ROUND(cantidad * precio_unitario * igv_porcentaje / 100, 2)) STORED,
    total_linea         NUMERIC(12,2) GENERATED ALWAYS AS
                            (ROUND(cantidad * precio_unitario * (1 + igv_porcentaje / 100), 2)) STORED,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW()
);

GRANT SELECT ON doc.factura                         TO authenticated;
GRANT SELECT ON doc.factura_detalle                 TO authenticated;
GRANT SELECT ON doc.factura_proveedor_detalle       TO authenticated;
GRANT SELECT ON doc.compra_factura_proveedor        TO authenticated;
GRANT SELECT ON inventario.lote_rollo_detalle       TO authenticated;

-- ── mes.tiempos_estandar_tenido ───────────────────────────────
-- Planning reference: expected duration for a dyeing step given
-- the color depth (valor), dyeing chemistry (tenido), and whether
-- antipilling treatment is included. Computed live at projection
-- time — NOT stored on partida_paso (which keeps
-- tiempo_estandar only for non-recipe steps copied from template).
CREATE TABLE mes.tiempos_estandar_tenido (
    id              SMALLINT    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    valor_id        SMALLINT    NOT NULL REFERENCES valor(id),
    tenido_id       INT         NOT NULL REFERENCES tenido(id),
    flg_antipilling BOOLEAN     NOT NULL DEFAULT false,
    duracion        INTERVAL    NOT NULL,
    flg_activo      BOOLEAN     NOT NULL DEFAULT true,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ
);

-- Only one active duration per (color depth, chemistry, antipilling).
CREATE UNIQUE INDEX uq_tiempos_estandar_tenido_activo
    ON mes.tiempos_estandar_tenido(valor_id, tenido_id, flg_antipilling)
    WHERE flg_activo = true;

-- ── mes.tiempos_estandar_lavado ───────────────────────────────
-- Planning reference: expected duration for a wash cycle given the
-- machine wash type. Looked up via receta.lavado_maquina.tipo_lavado_mq_id.
CREATE TABLE mes.tiempos_estandar_lavado (
    id                  SMALLINT    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo_lavado_mq_id   SMALLINT    NOT NULL REFERENCES tipo_lavado_maquina(id),
    duracion            INTERVAL    NOT NULL,
    flg_activo          BOOLEAN     NOT NULL DEFAULT true,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ
);

-- Only one active duration per wash type.
CREATE UNIQUE INDEX uq_tiempos_estandar_lavado_activo
    ON mes.tiempos_estandar_lavado(tipo_lavado_mq_id)
    WHERE flg_activo = true;

-- ── Grants ────────────────────────────────────────────────────
GRANT USAGE ON SCHEMA doc TO authenticated;

/*
-- ═══════════════════════════════════════════════════════════════
-- REVERSAL — undoes step 7 in full. Run then comment back out.
-- DROP TABLE CASCADE removes triggers and indexes on each table.
-- Order: most-dependent first so cascades don't surprise.
-- ═══════════════════════════════════════════════════════════════

-- calidad (deepest dependents)
DROP TABLE IF EXISTS calidad.inspeccion_foto          CASCADE;
DROP TABLE IF EXISTS calidad.inspeccion_defecto       CASCADE;
DROP TABLE IF EXISTS calidad.inspeccion               CASCADE;
DROP TABLE IF EXISTS calidad.tipo_defecto             CASCADE;

-- doc billing documents
DROP TABLE IF EXISTS doc.factura_detalle              CASCADE;
DROP TABLE IF EXISTS doc.letra_factura                CASCADE;
DROP TABLE IF EXISTS doc.factura                      CASCADE;
DROP TABLE IF EXISTS doc.letra                        CASCADE;
DROP TABLE IF EXISTS doc.catalogo_precios             CASCADE;
DROP TABLE IF EXISTS doc.compra_guia_remision         CASCADE;
DROP TABLE IF EXISTS doc.compra_detalle               CASCADE;
DROP TABLE IF EXISTS doc.compra_factura_proveedor     CASCADE;
DROP TABLE IF EXISTS doc.compra                       CASCADE;
DROP TABLE IF EXISTS doc.factura_proveedor_detalle    CASCADE;
DROP TABLE IF EXISTS doc.factura_proveedor            CASCADE;

-- inventario extensions
DROP TABLE IF EXISTS inventario.lote_rollo_detalle    CASCADE;
DROP TABLE IF EXISTS inventario.pesaje                CASCADE;

-- doc logistics
DROP TABLE IF EXISTS doc.guia_remision_detalle        CASCADE;
DROP TABLE IF EXISTS doc.guia_remision                CASCADE;
DROP TABLE IF EXISTS doc.guia_remision_tipo           CASCADE;

-- mes execution layer
DROP TABLE IF EXISTS mes.partida_componente           CASCADE;
DROP TABLE IF EXISTS mes.partida_paso_ejecucion       CASCADE;
DROP TABLE IF EXISTS mes.programacion                 CASCADE;
DROP TABLE IF EXISTS mes.partida_paso                 CASCADE;
DROP TABLE IF EXISTS mes.lavado_maquina               CASCADE;
DROP TABLE IF EXISTS mes.tiempos_estandar_tenido      CASCADE;
DROP TABLE IF EXISTS mes.tiempos_estandar_lavado      CASCADE;

-- mes order layer
DROP TABLE IF EXISTS mes.partida_detalle              CASCADE;
DROP TABLE IF EXISTS mes.partida                      CASCADE;

-- mes master data
DROP TABLE IF EXISTS mes.empleado                     CASCADE;
DROP TABLE IF EXISTS mes.empleado_rol                 CASCADE;
DROP TABLE IF EXISTS mes.ruta_plantilla_detalle       CASCADE;
DROP TABLE IF EXISTS mes.ruta_plantilla               CASCADE;
DROP TABLE IF EXISTS mes.maquina                      CASCADE;
DROP TABLE IF EXISTS mes.maquina_tipo                 CASCADE;
DROP TABLE IF EXISTS mes.operacion                    CASCADE;

REVOKE USAGE ON SCHEMA doc FROM authenticated;
*/
