-- ═══════════════════════════════════════════════════════════════
-- Step 7: doc, mes, calidad tables
-- Depends on: Step 5 (foundation), Step 6 (receta)
-- Key FK chains:
--   doc.partida → cliente, prioridad, tenido, color_x_cliente (all legacy)
--   mes.orden_produccion → doc.partida
--   mes.orden_produccion_paso → receta.tenido
--   mes.lavado_maquina → receta.lavado_maquina
--   calidad.inspeccion → inventario.lote, mes.orden_produccion_paso
-- ═══════════════════════════════════════════════════════════════

-- ── doc.partida ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS doc.partida (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    numero int GENERATED BY DEFAULT AS IDENTITY,
    prioridad_id int REFERENCES prioridad(id),
    tercero_id INT NOT NULL REFERENCES tercero(id),
    tenido_id int NOT NULL REFERENCES tenido(id),
    color_x_cliente_id int NOT NULL REFERENCES color_x_cliente(id),
    articulo_tipo_id SMALLINT NOT NULL REFERENCES articulo_tipo(id),  -- fabric type for this batch (billing key); restricts assignable rolls
    malla text,
    rendimiento text,
    ancho text,
    flg_antipilling boolean NOT NULL DEFAULT false,
    fecha_acordada date,                           -- agreed delivery date with client (SAP: EDATU)
    estado partida_estado_enum NOT NULL DEFAULT 'CREADA',
    -- Billing axis — orthogonal to production state.
    -- Updated when doc.factura lines are issued against this order.
    estado_facturacion partida_facturacion_enum NOT NULL DEFAULT 'pendiente',
    fyh_programacion timestamptz,
    fyh_inicio timestamptz,
    fyh_fin timestamptz,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    flg_elm BOOL DEFAULT false,
    usr_elm INT,
    fyh_elm TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS doc.partida_detalle (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    partida_id bigint NOT NULL REFERENCES doc.partida(id),
    item_id int NOT NULL REFERENCES item(id),
    cantidad numeric(12,2) NOT NULL CHECK (cantidad > 0),
    unidad_id int NOT NULL REFERENCES unidad(id),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE (partida_id, item_id)
);

-- ── doc.guia_remision_tipo ────────────────────────────────────
CREATE TABLE IF NOT EXISTS doc.guia_remision_tipo (
    id  smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    nombre text,
    flg_emitida boolean NOT NULL,
    flg_cliente boolean,
    item_movimiento_tipo_id SMALLINT REFERENCES inventario.item_movimiento_tipo(id),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE(codigo_canon)
);
CREATE TRIGGER trg_bi_guia_remision_tipo_codigo_canon
BEFORE INSERT OR UPDATE ON doc.guia_remision_tipo
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

INSERT INTO doc.guia_remision_tipo (codigo, nombre, flg_emitida, flg_cliente) VALUES
    ('COMPRA_INGRESO',            'Compra – Ingreso de insumos',                       false, false),
    ('VENTA_EGRESO',              'Venta – Egreso de producto terminado',               true,  true),
    ('CLIENTE_ENVIO_PROCESO',     'Servicio – Recepción de material cliente',           false, true),
    ('DESPACHO_CLIENTE',          'Servicio – Despacho de material procesado a cliente',true,  true),
    ('DEVOLUCION_CLIENTE_CRUDO',  'Devolución a cliente (rollos sin procesar)',         true,  true),
    ('DEVOLUCION_PROVEEDOR',      'Devolución a proveedor',                            true,  false);

UPDATE doc.guia_remision_tipo grt
SET item_movimiento_tipo_id = imt.id
FROM inventario.item_movimiento_tipo imt
WHERE
    (grt.codigo = 'COMPRA_INGRESO'           AND imt.codigo = 'COMPRA_ING')
 OR (grt.codigo = 'VENTA_EGRESO'             AND imt.codigo = 'VENTA_EGR')
 OR (grt.codigo = 'CLIENTE_ENVIO_PROCESO'    AND imt.codigo = 'SERV_ING')
 OR (grt.codigo = 'DESPACHO_CLIENTE'         AND imt.codigo = 'SERV_EGR')
 OR (grt.codigo = 'DEVOLUCION_CLIENTE_CRUDO' AND imt.codigo = 'DEV_CLI_EGR')
 OR (grt.codigo = 'DEVOLUCION_PROVEEDOR'     AND imt.codigo = 'DEV_PROV_EGR');

INSERT INTO doc.guia_remision_tipo (codigo, nombre, flg_emitida, flg_cliente, item_movimiento_tipo_id)
SELECT 'DEVOLUCION_CLIENTE_VENTA', 'Devolución de cliente (producto vendido)', false, true, imt.id
FROM inventario.item_movimiento_tipo imt WHERE imt.codigo = 'DEV_CLI_ING';

INSERT INTO doc.guia_remision_tipo (codigo, nombre, flg_emitida, flg_cliente, item_movimiento_tipo_id)
SELECT 'DEVOLUCION_CLIENTE_SERVICIO', 'Devolución de cliente (material de servicio)', false, true, imt.id
FROM inventario.item_movimiento_tipo imt WHERE imt.codigo = 'SERV_DEV_ING';

-- ── doc.guia_remision ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS doc.guia_remision (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    guia_remision_tipo_id smallint NOT NULL REFERENCES doc.guia_remision_tipo(id),
    tercero_id  INT NOT NULL REFERENCES tercero(id),  -- the external party; direction derived from guia_remision_tipo.flg_emitida
    serie TEXT NOT NULL,
    correlativo TEXT NOT NULL,
    fecha_emision TIMESTAMPTZ NOT NULL,
    fecha_recepcion TIMESTAMPTZ DEFAULT now(),
    usr_cre int,
    fyh_cre timestamptz DEFAULT NOW(),
    usr_mod int,
    fyh_mod timestamptz,
    flg_elm BOOL DEFAULT false,
    usr_elm INT,
    fyh_elm TIMESTAMPTZ,
    UNIQUE (tercero_id, serie, correlativo, guia_remision_tipo_id)
);

-- ── doc.guia_remision_detalle ─────────────────────────────────
CREATE TABLE IF NOT EXISTS doc.guia_remision_detalle (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    guia_remision_id BIGINT NOT NULL REFERENCES doc.guia_remision(id),
    item_id INT NOT NULL REFERENCES item(id),
    lote_id int REFERENCES inventario.lote(id),
    ubicacion_id int REFERENCES inventario.ubicacion(id),
    cantidad NUMERIC(12,2) NOT NULL CHECK (cantidad > 0),
    UNIQUE (guia_remision_id, item_id, lote_id, ubicacion_id)
);

-- ── inventario.pesaje ─────────────────────────────────────────
-- Placed here (after mes.orden_produccion will be defined) — forward ref OK
-- because it's only a FK and mes schema created in step 1.
-- Actually pesaje references mes.orden_produccion — must come after.
-- → Defined after mes.orden_produccion below.

-- ── mes.operacion ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mes.operacion (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    nombre text NOT NULL,
    requiere_receta boolean DEFAULT false,
    requiere_maquina boolean DEFAULT true,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE (nombre),
    UNIQUE (codigo_canon)
);
CREATE TRIGGER trg_bi_operacion_codigo_canon
BEFORE INSERT OR UPDATE ON mes.operacion
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

INSERT INTO mes.operacion (codigo, nombre, requiere_receta) VALUES
    ('TERMOFIJADO',  'Termofijado',  false),
    ('TENIDO',       'Teñido',       true),
    ('LAVADO_HIDRO', 'Lavado Hidro', true),
    ('SECADO',       'Secado',       false),
    ('PLANCHADO',    'Planchado',    false),
    ('PERCHADO',     'Perchado',     false),
    ('COMPACTADO',   'Compactado',   false),
    ('VOLTEADO',     'Volteado',     false),
    ('MATIZADO',     'Matizado',     true)
ON CONFLICT (codigo) DO NOTHING;

-- ── mes.maquina_tipo ──────────────────────────────────────────
CREATE TABLE mes.maquina_tipo (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    nombre text,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE(codigo_canon),
    UNIQUE(nombre)
);
CREATE TRIGGER trg_bi_maquina_tipo_codigo_canon
BEFORE INSERT OR UPDATE ON mes.maquina_tipo
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

-- ── mes.maquina ───────────────────────────────────────────────
CREATE TABLE mes.maquina (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    nombre text NOT NULL,
    maquina_tipo_id smallint REFERENCES mes.maquina_tipo(id),
    estado_actual maquina_estado_enum NOT NULL DEFAULT 'espera',
    ultimo_mantenimiento timestamptz,
    horas_totales int,
    capacidad_min_kg int NOT NULL CHECK (capacidad_min_kg > 0),
    capacidad_max_kg int NOT NULL CHECK (capacidad_max_kg >= capacidad_min_kg),
    relacion_bano numeric(5,2),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    flg_elm bool DEFAULT false,
    usr_elm int,
    fyh_elm TIMESTAMPTZ,
    UNIQUE(codigo_canon)
);
CREATE TRIGGER trg_bi_maquina_codigo_canon
BEFORE INSERT OR UPDATE ON mes.maquina
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

DROP TRIGGER IF EXISTS trg_bi_gen_codigo_maquina ON mes.maquina;
CREATE TRIGGER trg_bi_gen_codigo_maquina
BEFORE INSERT ON mes.maquina
FOR EACH ROW EXECUTE FUNCTION mes.fn_trg_gen_codigo_maquina();

-- ── mes.empleado_rol ──────────────────────────────────────────
CREATE TABLE mes.empleado_rol (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    nombre text NOT NULL,
    descripcion text,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE(codigo_canon)
);
CREATE TRIGGER trg_bi_empleado_rol_codigo_canon
BEFORE INSERT OR UPDATE ON mes.empleado_rol
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

-- ── mes.empleado ──────────────────────────────────────────────
CREATE TABLE mes.empleado (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre text,
    apellido text,
    rol_id smallint NOT NULL REFERENCES mes.empleado_rol(id),
    turno_id smallint REFERENCES turno(id),   -- legacy FK
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ
);

-- ── mes.ruta_plantilla ────────────────────────────────────────
CREATE TABLE mes.ruta_plantilla (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    flg_elm boolean DEFAULT false,
    usr_elm int,
    fyh_elm timestamptz
);

CREATE TABLE mes.ruta_plantilla_detalle (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ruta_plantilla_id int NOT NULL REFERENCES mes.ruta_plantilla(id),
    operacion_id smallint NOT NULL REFERENCES mes.operacion(id),
    secuencia smallint NOT NULL,
    ph numeric(4,2),
    temperatura numeric(5,2),
    tiempo_estandar int,
    UNIQUE (ruta_plantilla_id, secuencia)
);

-- ── mes.orden_produccion ──────────────────────────────────────
CREATE TABLE mes.orden_produccion (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    partida_id bigint NOT NULL REFERENCES doc.partida(id),
    tipo orden_produccion_tipo_enum NOT NULL,
    orden_origen_id bigint REFERENCES mes.orden_produccion(id),
    estado orden_produccion_estado_enum NOT NULL DEFAULT 'CREADA',
    fyh_cre timestamptz DEFAULT now(),
    fyh_inicio timestamptz,
    fyh_fin timestamptz,
    usr_cre int,
    flg_elm BOOL DEFAULT false,
    usr_elm INT,
    fyh_elm TIMESTAMPTZ
);

-- ── inventario.pesaje ─────────────────────────────────────────
CREATE TABLE inventario.pesaje (
    id                  INT  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    lote_id             INT  NOT NULL REFERENCES inventario.lote(id),
    -- Context: one of these is populated depending on when weighing occurred.
    -- partida_id: ingress weighing before production (primary flow).
    -- orden_produccion_id: post-assignment correction (rare).
    partida_id          BIGINT REFERENCES doc.partida(id),
    orden_produccion_id BIGINT REFERENCES mes.orden_produccion(id),
    peso_real           NUMERIC(10,2),
    observacion         TEXT,
    usr_cre             INT,
    fyh_cre             TIMESTAMPTZ DEFAULT NOW()
);

-- ── mes.orden_produccion_paso ─────────────────────────────────
CREATE TABLE mes.orden_produccion_paso (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    orden_produccion_id bigint NOT NULL REFERENCES mes.orden_produccion(id),
    secuencia smallint NOT NULL,
    operacion_id smallint NOT NULL REFERENCES mes.operacion(id),
    maquina_asignada_id int REFERENCES mes.maquina(id),
    ph numeric(4,2),
    temperatura numeric(5,2),
    tiempo_estandar int,
    relacion_bano numeric(5,2),
    receta_id int REFERENCES receta.tenido(id),
    estado orden_produccion_paso_estado_enum DEFAULT 'PENDIENTE',
    empleado_id smallint REFERENCES mes.empleado(id),
    flg_genera_produccion bool DEFAULT false,
    fyh_inicio timestamptz,
    fyh_fin timestamptz,
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE (orden_produccion_id, secuencia)
);

-- ── mes.orden_produccion_item ─────────────────────────────────
CREATE TABLE mes.orden_produccion_item (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    orden_produccion_id bigint NOT NULL REFERENCES mes.orden_produccion(id),
    item_id int NOT NULL REFERENCES item(id),
    lote_id int NOT NULL REFERENCES inventario.lote(id),
    ubicacion_id int NOT NULL REFERENCES inventario.ubicacion(id),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE(orden_produccion_id, lote_id, ubicacion_id)
);

-- ── mes.orden_produccion_paso_item ────────────────────────────
CREATE TABLE mes.orden_produccion_paso_item (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    orden_produccion_paso_id bigint NOT NULL REFERENCES mes.orden_produccion_paso(id),
    orden_produccion_item_id int NOT NULL REFERENCES mes.orden_produccion_item(id),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod int,
    fyh_mod TIMESTAMPTZ,
    UNIQUE (orden_produccion_paso_id, orden_produccion_item_id)
);

-- ── mes.programacion ─────────────────────────────────────────
CREATE TABLE mes.programacion (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actividad_tipo TEXT NOT NULL,
    actividad_id   BIGINT NOT NULL,
    maquina_id int NOT NULL REFERENCES mes.maquina(id),
    fecha date NOT NULL,
    secuencia smallint NOT NULL,
    nota text,
    usr_cre int,
    fyh_cre timestamptz DEFAULT now(),
    usr_mod int,
    fyh_mod timestamptz,
    UNIQUE (maquina_id, fecha, secuencia),
    CONSTRAINT chk_programacion_actividad_tipo
        CHECK (actividad_tipo IN ('ORDEN_PRODUCCION_PASO', 'LAVADO_MAQUINA'))
);

-- ── mes.lavado_maquina ────────────────────────────────────────
CREATE TABLE mes.lavado_maquina (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_id   INT NOT NULL REFERENCES receta.lavado_maquina(id),
    maquina_id  INT NOT NULL REFERENCES mes.maquina(id),
    estado      orden_produccion_paso_estado_enum NOT NULL DEFAULT 'PENDIENTE',
    empleado_id SMALLINT REFERENCES mes.empleado(id),
    fyh_inicio  TIMESTAMPTZ,
    fyh_fin     TIMESTAMPTZ,
    nota        TEXT,
    usr_cre     INT,
    fyh_cre     TIMESTAMPTZ DEFAULT NOW(),
    usr_mod     INT,
    fyh_mod     TIMESTAMPTZ
);

-- ── calidad ───────────────────────────────────────────────────
CREATE TABLE calidad.inspeccion (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    lote_id int NOT NULL REFERENCES inventario.lote(id),
    orden_produccion_paso_id bigint REFERENCES mes.orden_produccion_paso(id),
    resultado calidad_estado_enum NOT NULL,
    observacion text,
    empleado_id int REFERENCES mes.empleado(id),
    fyh_inspeccion timestamptz DEFAULT now(),
    usr_cre int,
    fyh_cre TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE calidad.tipo_defecto (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL,
    UNIQUE (codigo_canon),
    nombre text NOT NULL,
    descripcion text,
    severidad smallint DEFAULT 1,
    activo boolean DEFAULT true
);
CREATE TRIGGER trg_bi_tipo_defecto_codigo_canon
BEFORE INSERT OR UPDATE ON calidad.tipo_defecto
FOR EACH ROW
EXECUTE FUNCTION public.fn_trg_set_codigo_canon();

INSERT INTO calidad.tipo_defecto (codigo, nombre, descripcion, severidad) VALUES
('LINEA',            'Línea / Raya',                  'Línea visible en sentido de urdimbre o trama',               2),
('MANCHA',           'Mancha',                        'Mancha de aceite, óxido, suciedad u otro agente',            2),
('HUECO',            'Hueco',                         'Perforación o rotura en la tela',                            3),
('HILO_ROTO',        'Hilo roto',                     'Filamento o hilo cortado visible en la superficie',          2),
('CAIDA_MALLA',      'Caída de malla',                'Malla suelta o corrida en tejido de punto',                  3),
('HILO_GRUESO',      'Hilo grueso / delgado',         'Variación de título de hilo visible',                        1),
('CONTAMINACION',    'Contaminación / Fibra extraña', 'Fibra o material ajeno atrapado en el tejido',              2),
('TONO_DESIGUAL',    'Tono desigual',                 'Variación de tono dentro del mismo rollo',                   2),
('BARRADO',          'Barrado',                       'Franjas horizontales por diferencia de tensión o lote',      3),
('PILLING',          'Pilling',                       'Bolitas de fibra en la superficie',                          1),
('PESO_FUERA_SPEC',  'Peso fuera de especificación',  'Gramaje (g/m²) fuera de tolerancia',                        2),
('ANCHO_FUERA_SPEC', 'Ancho fuera de especificación', 'Ancho del rollo fuera de tolerancia',                       2),
('ENCOGIMIENTO',     'Encogimiento excesivo',         'Encogimiento superior al permitido tras lavado/proceso',     3),
('ARRUGA',           'Arruga / Quiebre',              'Marca de pliegue permanente',                                1),
('ORILLO_DEFECTUOSO','Orillo defectuoso',             'Orillo enrollado, cortado o irregular',                      1);

CREATE TABLE calidad.inspeccion_defecto (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inspeccion_id bigint NOT NULL REFERENCES calidad.inspeccion(id),
    tipo_defecto_id smallint NOT NULL REFERENCES calidad.tipo_defecto(id),
    cantidad smallint DEFAULT 1,
    observacion text
);

CREATE TABLE calidad.inspeccion_foto (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inspeccion_defecto_id bigint NOT NULL REFERENCES calidad.inspeccion_defecto(id),
    ruta_archivo text NOT NULL,
    etiqueta text,
    observacion text,
    usr_cre int,
    fyh_cre timestamptz DEFAULT now()
);

-- ── doc.factura_proveedor ─────────────────────────────────────
CREATE TABLE doc.factura_proveedor (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tercero_id   INT NOT NULL REFERENCES tercero(id),
    serie       TEXT NOT NULL,
    numero      INT  NOT NULL,
    fecha_emision       DATE NOT NULL,
    fecha_vencimiento   DATE,
    tipo_pago   tipo_pago_enum NOT NULL DEFAULT 'al contado',
    moneda      CHAR(3) NOT NULL DEFAULT 'USD',
    tipo_cambio NUMERIC(10,4),
    subtotal    NUMERIC(12,2) NOT NULL DEFAULT 0,
    igv         NUMERIC(12,2) NOT NULL DEFAULT 0,
    total       NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado_pago estado_pago_enum NOT NULL DEFAULT 'pendiente',
    observacion TEXT,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ,
    UNIQUE (tercero_id, serie, numero),
    CONSTRAINT chk_factura_montos CHECK (
        subtotal > 0 AND igv >= 0 AND total > 0
        AND ABS(total - (subtotal + igv)) < 0.01
    )
);

CREATE TABLE doc.compra (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tercero_id   INT NOT NULL REFERENCES tercero(id),
    factura_proveedor_id BIGINT REFERENCES doc.factura_proveedor(id),
    fecha       DATE NOT NULL DEFAULT CURRENT_DATE,
    observacion TEXT,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ,
    flg_elm BOOLEAN NOT NULL DEFAULT FALSE,
    usr_elm INT,  fyh_elm TIMESTAMPTZ
);

CREATE TABLE doc.compra_detalle (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    compra_id       BIGINT NOT NULL REFERENCES doc.compra(id),
    item_id         INT    NOT NULL REFERENCES item(id),
    cantidad        NUMERIC(12,4) NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12,4) NOT NULL CHECK (precio_unitario >= 0),
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE doc.compra_guia_remision (
    compra_id        BIGINT NOT NULL REFERENCES doc.compra(id),
    guia_remision_id BIGINT NOT NULL REFERENCES doc.guia_remision(id),
    PRIMARY KEY (compra_id, guia_remision_id)
);

CREATE TABLE doc.letra (
    id                   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    factura_proveedor_id BIGINT NOT NULL REFERENCES doc.factura_proveedor(id),
    numero               TEXT,
    monto                NUMERIC(12,2) NOT NULL CHECK (monto > 0),
    fecha_giro           DATE,
    fecha_vencimiento    DATE NOT NULL,
    banco                TEXT,
    estado               letra_estado_enum NOT NULL DEFAULT 'emitida',
    fecha_pago           DATE,
    observacion          TEXT,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ
);

-- ── doc.factura ───────────────────────────────────────────────
-- Emitted customer invoices (facturas de venta / boletas).
-- Financial closure document for one or more partidas.
-- SUNAT FE integration: push to Siigo API (or similar) after estado = 'emitida'.
--
-- tipo_comprobante codes follow SUNAT standard:
--   '01' = Factura        (RUC buyer, full tax credit)
--   '03' = Boleta de Venta (DNI/RUC buyer, no credit)
--   '07' = Nota de Crédito
--   '08' = Nota de Débito
CREATE TABLE doc.factura (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo_comprobante    CHAR(2) NOT NULL DEFAULT '01'
                            CHECK (tipo_comprobante IN ('01','03','07','08')),
    serie               TEXT NOT NULL,          -- e.g. F001, B001, T001
    numero              INT  NOT NULL,          -- correlative
    tercero_id          INT  NOT NULL REFERENCES tercero(id),
    fecha_emision       DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_vencimiento   DATE,
    moneda              CHAR(3) NOT NULL DEFAULT 'PEN',
    tipo_cambio         NUMERIC(10,4),          -- only relevant when moneda = 'USD'
    subtotal            NUMERIC(12,2) NOT NULL DEFAULT 0,
    igv                 NUMERIC(12,2) NOT NULL DEFAULT 0,   -- 18 % standard rate
    total               NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado              factura_estado_enum NOT NULL DEFAULT 'borrador',
    -- Nota de crédito/débito linkage (nullable — only set for 07/08 types)
    factura_origen_id   BIGINT REFERENCES doc.factura(id),
    observacion         TEXT,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ,
    flg_elm BOOL DEFAULT false,
    usr_elm INT, fyh_elm TIMESTAMPTZ,
    UNIQUE (serie, numero),
    CONSTRAINT chk_factura_montos CHECK (
        subtotal >= 0 AND igv >= 0 AND total >= 0
        AND ABS(total - (subtotal + igv)) < 0.01
    ),
    CONSTRAINT chk_nota_requiere_origen CHECK (
        tipo_comprobante NOT IN ('07','08') OR factura_origen_id IS NOT NULL
    )
);

-- ── doc.factura_detalle ────────────────────────────────────────
-- One line per billable item / service.
-- partida_id links back to the sales order for billing-to-order reconciliation.
-- igv_porcentaje allows 0% for IGV-exempt items (e.g. exported goods).
CREATE TABLE doc.factura_detalle (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    factura_id          BIGINT NOT NULL REFERENCES doc.factura(id),
    -- Sales order line this invoice line covers (nullable for ad-hoc lines)
    partida_id          BIGINT REFERENCES doc.partida(id),
    descripcion         TEXT   NOT NULL,
    cantidad            NUMERIC(12,4) NOT NULL CHECK (cantidad > 0),
    unidad_id           INT    NOT NULL REFERENCES unidad(id),
    precio_unitario     NUMERIC(12,4) NOT NULL CHECK (precio_unitario >= 0),
    igv_porcentaje      NUMERIC(5,2)  NOT NULL DEFAULT 18
                            CHECK (igv_porcentaje IN (0, 18)),
    -- Stored computed columns avoid rounding drift across lines
    subtotal_linea      NUMERIC(12,2) GENERATED ALWAYS AS
                            (ROUND(cantidad * precio_unitario, 2)) STORED,
    igv_linea           NUMERIC(12,2) GENERATED ALWAYS AS
                            (ROUND(cantidad * precio_unitario * igv_porcentaje / 100, 2)) STORED,
    total_linea         NUMERIC(12,2) GENERATED ALWAYS AS
                            (ROUND(cantidad * precio_unitario * (1 + igv_porcentaje / 100), 2)) STORED,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW()
);

GRANT SELECT ON doc.factura         TO authenticated;
GRANT SELECT ON doc.factura_detalle TO authenticated;

-- ── mes.tiempos_estandar_tenido ───────────────────────────────
-- Planning reference: expected duration for a dyeing step given
-- the color depth (valor), dyeing chemistry (tenido), and whether
-- antipilling treatment is included. Computed live at projection
-- time — NOT stored on orden_produccion_paso (which keeps
-- tiempo_estandar only for non-recipe steps copied from template).
CREATE TABLE mes.tiempos_estandar_tenido (
    id              SMALLINT    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    valor_id        SMALLINT    NOT NULL REFERENCES valor(id),
    tenido_id       INT         NOT NULL REFERENCES tenido(id),
    flg_antipilling BOOLEAN     NOT NULL DEFAULT false,
    duracion        INTERVAL    NOT NULL,
    flg_activo      BOOLEAN     NOT NULL DEFAULT true,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ
);

-- Only one active duration per (color depth, chemistry, antipilling).
CREATE UNIQUE INDEX uq_tiempos_estandar_tenido_activo
    ON mes.tiempos_estandar_tenido(valor_id, tenido_id, flg_antipilling)
    WHERE flg_activo = true;

-- ── mes.tiempos_estandar_lavado ───────────────────────────────
-- Planning reference: expected duration for a wash cycle given the
-- machine wash type. Looked up via receta.lavado_maquina.tipo_lavado_mq_id.
CREATE TABLE mes.tiempos_estandar_lavado (
    id                  SMALLINT    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo_lavado_mq_id   SMALLINT    NOT NULL REFERENCES tipo_lavado_maquina(id),
    duracion            INTERVAL    NOT NULL,
    flg_activo          BOOLEAN     NOT NULL DEFAULT true,
    usr_cre INT, fyh_cre TIMESTAMPTZ DEFAULT NOW(),
    usr_mod INT, fyh_mod TIMESTAMPTZ
);

-- Only one active duration per wash type.
CREATE UNIQUE INDEX uq_tiempos_estandar_lavado_activo
    ON mes.tiempos_estandar_lavado(tipo_lavado_mq_id)
    WHERE flg_activo = true;

-- ── Grants ────────────────────────────────────────────────────
GRANT USAGE ON SCHEMA doc TO authenticated;
