CREATE TABLE IF NOT EXISTS public.receta2
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    color_x_cliente_id smallint,
    tipo_articulo_id smallint,
    tenido_id smallint,
    fibra smallint,
    fyh_cre timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    usr_cre text COLLATE pg_catalog."default" DEFAULT CURRENT_USER,
    flg_activo boolean DEFAULT true,
    flg_antipilling boolean DEFAULT false,
    tipo_receta_id smallint,
    fyh_cre_tz timestamp with time zone DEFAULT now(),
    flg_produccion boolean DEFAULT false,
    fyh_produccion timestamp with time zone,
    CONSTRAINT receta2_pkey PRIMARY KEY (id),
    CONSTRAINT receta2_fk_color_x_cliente_fkey FOREIGN KEY (color_x_cliente_id)
        REFERENCES public.color_x_cliente (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT receta2_fk_tenido_fkey FOREIGN KEY (tenido_id)
        REFERENCES public.tenido (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT receta2_fk_tipo_articulo_fkey FOREIGN KEY (tipo_articulo_id)
        REFERENCES public.tipo_articulo (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT receta2_fk_tipo_receta_fkey FOREIGN KEY (tipo_receta_id)
        REFERENCES public.tipo_receta (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
CREATE TABLE IF NOT EXISTS public.receta_lavado_maquina
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tipo_lavado_mq_id smallint,
    valor_origen_id smallint,
    valor_destino_id smallint,
    fyh_cre timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    usr_cre text COLLATE pg_catalog."default" DEFAULT CURRENT_USER,
    flg_activo boolean DEFAULT true,
    fyh_cre_tz timestamp with time zone DEFAULT now(),
    CONSTRAINT receta_lavado_maquina_pkey PRIMARY KEY (id),
    CONSTRAINT receta_lavado_maquina_fk_tipo_lavado_mq_fkey FOREIGN KEY (tipo_lavado_mq_id)
        REFERENCES public.tipo_lavado_maquina (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT receta_lavado_maquina_fk_valor_destino_fkey FOREIGN KEY (valor_destino_id)
        REFERENCES public.valor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT receta_lavado_maquina_fk_valor_origen_fkey FOREIGN KEY (valor_origen_id)
        REFERENCES public.valor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
CREATE TABLE IF NOT EXISTS public.receta_lavado_maquina_x_insumo
(
    receta_lavado_mq_id integer,
    insumo_id smallint,
    cantidad numeric(10,4) NOT NULL,
    orden smallint NOT NULL,
    CONSTRAINT receta_lavado_maquina_x_insumo_fk_receta_lavado_mq_orden_key UNIQUE (receta_lavado_mq_id, orden),
    CONSTRAINT receta_lavado_maquina_x_insumo_fk_insumo_fkey FOREIGN KEY (insumo_id)
        REFERENCES public.insumo (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT receta_lavado_maquina_x_insumo_fk_receta_lavado_mq_fkey FOREIGN KEY (receta_lavado_mq_id)
        REFERENCES public.receta_lavado_maquina (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
CREATE TABLE IF NOT EXISTS public.receta_lavado_maquina_x_paso
(
    receta_lavado_mq_id integer,
    paso_id smallint,
    orden smallint NOT NULL,
    CONSTRAINT receta_lavado_maquina_x_paso_fk_receta_lavado_mq_orden_key UNIQUE (receta_lavado_mq_id, orden),
    CONSTRAINT receta_lavado_maquina_x_paso_fk_paso_fkey FOREIGN KEY (paso_id)
        REFERENCES public.paso (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT receta_lavado_maquina_x_paso_fk_receta_lavado_mq_fkey FOREIGN KEY (receta_lavado_mq_id)
        REFERENCES public.receta_lavado_maquina (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
CREATE TABLE IF NOT EXISTS public.receta_x_insumo
(
    receta_id integer,
    insumo_id smallint,
    cantidad numeric(8,4) NOT NULL,
    orden smallint NOT NULL,
    id integer NOT NULL DEFAULT nextval('receta_x_insumo_id_seq'::regclass),
    CONSTRAINT receta_x_insumo_fk_receta_orden_key UNIQUE (receta_id, orden),
    CONSTRAINT receta_x_insumo_fk_insumo_fkey FOREIGN KEY (insumo_id)
        REFERENCES public.insumo (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT receta_x_insumo_fk_receta_fkey FOREIGN KEY (receta_id)
        REFERENCES public.receta2 (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
CREATE TABLE IF NOT EXISTS public.receta_x_paso
(
    receta_id integer,
    paso_id smallint,
    orden smallint NOT NULL,
    id integer NOT NULL DEFAULT nextval('receta_x_paso_id_seq'::regclass),
    CONSTRAINT receta_x_paso_fk_receta_orden_key UNIQUE (receta_id, orden),
    CONSTRAINT receta_x_paso_fk_paso_fkey FOREIGN KEY (paso_id)
        REFERENCES public.paso (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT receta_x_paso_fk_receta_fkey FOREIGN KEY (receta_id)
        REFERENCES public.receta2 (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)




-- ═══════════════════════════════════════════════════════════════
-- MIGRATED MODEL (new tables — replaces flat receta_x_paso/receta_x_insumo)
-- Headers (receta2, receta_lavado_maquina) stay as-is above.
-- Old child tables (receta_x_paso, receta_x_insumo, receta_lavado_maquina_x_*)
-- kept above for reference — drop after data migration.
-- ═══════════════════════════════════════════════════════════════

-- Recipe operation catalog (chemistry actions within a recipe)
-- NOT mes.operacion — these are micro-level chemistry steps,
-- not macro-level production service steps
CREATE TABLE receta_operacion (
    id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL
);

CREATE TRIGGER trg_bi_receta_operacion_codigo_canon
BEFORE INSERT OR UPDATE ON receta_operacion
FOR EACH ROW
EXECUTE FUNCTION fn_trg_set_codigo_canon();

INSERT INTO receta_operacion (codigo, nombre) VALUES
    ('TINTURA',           'Tintura'),
    ('LAVADO',            'Lavado'),
    ('LAVADO_REDUCTIVO',  'Lavado Reductivo'),
    ('BLANQUEO_QUIMICO',  'Blanqueo Químico'),
    ('BLANQUEO_OPTICO',   'Blanqueo Óptico'),
    ('DESCRUDE',          'Descrude'),
    ('NEUTRALIZADO',      'Neutralizado'),
    ('SUAVIZADO',         'Suavizado'),
    ('FIJADO',            'Fijado'),
    ('JABONADO',          'Jabonado'),
    ('ENJUAGUE',          'Enjuague'),
    ('MATIZADO',          'Matizado'),
    ('ANTIPILLING',       'Antipilling'),
    ('REGULACION_PH',     'Regulación de pH'),
    ('SIMULTANEO',        'Simultáneo'),
    ('DESMONTADO',        'Desmontado'),
    ('REBAJE',            'Rebaje');

-- ───────────────────────────────────────
-- DYEING RECIPE — hierarchical: paso → insumo
-- ───────────────────────────────────────

CREATE TABLE receta_paso (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_id INT NOT NULL REFERENCES receta2(id),
    receta_operacion_id SMALLINT NOT NULL REFERENCES receta_operacion(id),
    orden SMALLINT NOT NULL,
    ph NUMERIC(4,2),
    temperatura NUMERIC(5,2),
    tiempo_min SMALLINT,
    nota TEXT,
    UNIQUE(receta_id, orden)
);

CREATE TABLE receta_paso_insumo (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_paso_id INT NOT NULL REFERENCES receta_paso(id) ON DELETE CASCADE,
    item_id INT NOT NULL REFERENCES item(id),
    cantidad NUMERIC(8,4) NOT NULL,
    orden SMALLINT NOT NULL,
    UNIQUE(receta_paso_id, orden)
);

-- ───────────────────────────────────────
-- MACHINE WASH RECIPE — same hierarchy: paso → insumo
-- ───────────────────────────────────────

CREATE TABLE receta_lavado_maquina_paso (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_lavado_maquina_id INT NOT NULL REFERENCES receta_lavado_maquina(id),
    receta_operacion_id SMALLINT NOT NULL REFERENCES receta_operacion(id),
    orden SMALLINT NOT NULL,
    ph NUMERIC(4,2),
    temperatura NUMERIC(5,2),
    tiempo_min SMALLINT,
    nota TEXT,
    UNIQUE(receta_lavado_maquina_id, orden)
);

CREATE TABLE receta_lavado_maquina_paso_insumo (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_lavado_maquina_paso_id INT NOT NULL REFERENCES receta_lavado_maquina_paso(id) ON DELETE CASCADE,
    item_id INT NOT NULL REFERENCES item(id),
    cantidad NUMERIC(8,4) NOT NULL,
    orden SMALLINT NOT NULL,
    UNIQUE(receta_lavado_maquina_paso_id, orden)
);

-- ───────────────────────────────────────
-- GRANTS
-- ───────────────────────────────────────

GRANT SELECT ON receta_operacion TO authenticated;
GRANT SELECT ON receta_paso TO authenticated;
GRANT SELECT ON receta_paso_insumo TO authenticated;
GRANT SELECT ON receta_lavado_maquina_paso TO authenticated;
GRANT SELECT ON receta_lavado_maquina_paso_insumo TO authenticated;

-- ═══════════════════════════════════════════════════════════════
-- COLOR DEVELOPMENT (separate domain)
-- ═══════════════════════════════════════════════════════════════
---evaluar denormalizar al header de recta nomas
CREATE TABLE IF NOT EXISTS public.desarrollo_color
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    color_x_cliente_id smallint,
    tipo_articulo_id smallint,
    tenido_id smallint,
    fecha_ingreso date NOT NULL,
    estado_desarrollo_color_id smallint,
    fecha_estado_actual date,
    descripcion text COLLATE pg_catalog."default",
    fyh_cre timestamp without time zone DEFAULT now(),
    fyh_cre_tz timestamp with time zone DEFAULT now(),
    CONSTRAINT desarrollo_color_pkey PRIMARY KEY (id),
    CONSTRAINT uq_desarrollo UNIQUE (color_x_cliente_id, tipo_articulo_id, tenido_id),
    CONSTRAINT desarrollo_color_fk_color_x_cliente_fkey FOREIGN KEY (color_x_cliente_id)
        REFERENCES public.color_x_cliente (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT desarrollo_color_fk_estado_desarrollo_color_fkey FOREIGN KEY (estado_desarrollo_color_id)
        REFERENCES public.estado_desarrollo_color (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT desarrollo_color_fk_tenido_fkey FOREIGN KEY (tenido_id)
        REFERENCES public.tenido (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT desarrollo_color_fk_tipo_articulo_fkey FOREIGN KEY (tipo_articulo_id)
        REFERENCES public.tipo_articulo (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)


