-- ═══════════════════════════════════════════════════════════════
-- receta SCHEMA — recipe master data (process engineering domain)
--
-- Domain split:
--   receta.tenido         → dyeing recipe formula
--   receta.lavado_maquina → machine wash recipe formula
--   receta.operacion      → chemistry step catalog
--
-- NOTE: receta.operacion  = micro-level chemistry steps within a recipe
--       mes.operacion     = macro-level production operations (TENIDO, SECADO…)
--       Same name, different granularity, different schema, never JOINed together.
--
-- Consumers:
--   mes.orden_produccion_paso.receta_id    → receta.tenido(id)
--   mes.lavado_maquina.receta_id           → receta.lavado_maquina(id)
-- ═══════════════════════════════════════════════════════════════

CREATE SCHEMA IF NOT EXISTS receta;

-- ───────────────────────────────────────
-- Recipe development state catalog
-- (public schema — legacy table extended with codigo column)
-- Used by: receta.tenido.estado_id
-- ───────────────────────────────────────

CREATE TABLE IF NOT EXISTS estado_desarrollo_color (
    id     SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre TEXT     NOT NULL,
    codigo TEXT     NOT NULL UNIQUE
);
INSERT INTO estado_desarrollo_color (nombre, codigo) VALUES
    ('Ingresado',          'INGRESADO'),
    ('En Desarrollo',      'EN_DESARROLLO'),
    ('Enviado al Cliente', 'ENVIADO_CLIENTE'),
    ('Aprobado',           'APROBADO'),
    ('Rechazado',          'RECHAZADO'),
    ('Cancelado',          'CANCELADO'),
    ('Re Lab',             'RE_LAB'),
    ('Histórico',          'HISTORICO');

-- ───────────────────────────────────────
-- Chemistry operation catalog
-- ───────────────────────────────────────

CREATE TABLE receta.operacion (
    id           SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo       TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL UNIQUE,
    nombre       TEXT NOT NULL
);

CREATE TRIGGER trg_bi_receta_operacion_codigo_canon
BEFORE INSERT OR UPDATE ON receta.operacion
FOR EACH ROW
EXECUTE FUNCTION fn_trg_set_codigo_canon();

INSERT INTO receta.operacion (codigo, nombre) VALUES
    ('TINTURA',           'Tintura'),
    ('LAVADO',            'Lavado'),
    ('LAVADO_REDUCTIVO',  'Lavado Reductivo'),
    ('BLANQUEO_QUIMICO',  'Blanqueo Químico'),
    ('BLANQUEO_OPTICO',   'Blanqueo Óptico'),
    ('DESCRUDE',          'Descrude'),
    ('NEUTRALIZADO',      'Neutralizado'),
    ('SUAVIZADO',         'Suavizado'),
    ('FIJADO',            'Fijado'),
    ('JABONADO',          'Jabonado'),
    ('ENJUAGUE',          'Enjuague'),
    ('MATIZADO',          'Matizado'),
    ('ANTIPILLING',       'Antipilling'),
    ('REGULACION_PH',     'Regulación de pH'),
    ('SIMULTANEO',        'Simultáneo'),
    ('DESMONTADO',        'Desmontado'),
    ('REBAJE',            'Rebaje');

-- ───────────────────────────────────────
-- Dyeing recipe header
-- (migrated from public.receta2)
-- ───────────────────────────────────────

CREATE TABLE receta.tenido (
    id                 INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color_x_cliente_id INT      REFERENCES color_x_cliente(id),
    articulo_id        INT      REFERENCES articulo(id),       -- replaces tipo_articulo_id + fibra
    tenido_id          INT      REFERENCES tenido(id),
    flg_antipilling    BOOLEAN  NOT NULL DEFAULT false,
    tipo_receta_id     SMALLINT REFERENCES tipo_receta(id),
    estado_id          SMALLINT NOT NULL REFERENCES estado_desarrollo_color(id),
    -- flg_activo REMOVED: derived — active = estado_id not in (RECHAZADO, CANCELADO, HISTORICO)
    -- flg_produccion: trigger-maintained. NEVER set manually — application sets estado_id only.
    flg_produccion     BOOLEAN  NOT NULL DEFAULT false,
    fyh_produccion     TIMESTAMPTZ,
    usr_cre            INT      REFERENCES profiles(id_usuario),
    fyh_cre            TIMESTAMPTZ DEFAULT now(),
    usr_mod            INT      REFERENCES profiles(id_usuario),
    fyh_mod            TIMESTAMPTZ
);

-- Trigger: maintains flg_produccion = (estado_id = APROBADO) automatically.
-- No hardcoded IDs — looks up APROBADO by codigo at write time.
CREATE OR REPLACE FUNCTION fn_trg_receta_tenido_flg_produccion()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_aprobado_id SMALLINT;
BEGIN
    SELECT id INTO v_aprobado_id FROM estado_desarrollo_color WHERE codigo = 'APROBADO';
    NEW.flg_produccion := (NEW.estado_id = v_aprobado_id);
    RETURN NEW;
END;$$;

CREATE TRIGGER trg_bi_receta_tenido_flg_produccion
BEFORE INSERT OR UPDATE OF estado_id ON receta.tenido
FOR EACH ROW EXECUTE FUNCTION fn_trg_receta_tenido_flg_produccion();

-- Enforces: at most one approved recipe per spec combination (color × article × dyebath × antipilling).
-- flg_produccion is trigger-maintained so no fragile hardcoded estado IDs in the index predicate.
CREATE UNIQUE INDEX uq_receta_tenido_aprobada
    ON receta.tenido(color_x_cliente_id, articulo_id, tenido_id, flg_antipilling)
    WHERE flg_produccion = true;

-- Dyeing recipe steps (ordered chemistry sequence within the recipe)
CREATE TABLE receta.tenido_paso (
    id           INT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_id    INT      NOT NULL REFERENCES receta.tenido(id),
    operacion_id SMALLINT NOT NULL REFERENCES receta.operacion(id),
    orden        SMALLINT NOT NULL,
    ph           NUMERIC(4,2),
    temperatura  NUMERIC(5,2),
    tiempo_min   SMALLINT,
    nota         TEXT,
    UNIQUE(receta_id, orden)
);

-- Chemicals per dyeing step
CREATE TABLE receta.tenido_paso_insumo (
    id       INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    paso_id  INT             NOT NULL REFERENCES receta.tenido_paso(id) ON DELETE CASCADE,
    item_id  INT             NOT NULL REFERENCES item(id),
    cantidad NUMERIC(8,4)   NOT NULL,
    orden    SMALLINT        NOT NULL,
    UNIQUE(paso_id, orden)
);

-- ───────────────────────────────────────
-- Machine wash recipe header
-- (migrated from public.receta_lavado_maquina)
-- ───────────────────────────────────────

CREATE TABLE receta.lavado_maquina (
    id                INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_lavado_mq_id SMALLINT REFERENCES tipo_lavado_maquina(id),
    valor_origen_id   SMALLINT REFERENCES valor(id),
    valor_destino_id  SMALLINT REFERENCES valor(id),
    flg_activo        BOOLEAN  DEFAULT true,
    usr_cre           INT      REFERENCES profiles(id_usuario),
    fyh_cre           TIMESTAMPTZ DEFAULT now(),
    usr_mod           INT      REFERENCES profiles(id_usuario),
    fyh_mod           TIMESTAMPTZ
);

-- Wash recipe steps
CREATE TABLE receta.lavado_maquina_paso (
    id           INT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_id    INT      NOT NULL REFERENCES receta.lavado_maquina(id),
    operacion_id SMALLINT NOT NULL REFERENCES receta.operacion(id),
    orden        SMALLINT NOT NULL,
    ph           NUMERIC(4,2),
    temperatura  NUMERIC(5,2),
    tiempo_min   SMALLINT,
    nota         TEXT,
    UNIQUE(receta_id, orden)
);

-- Chemicals per wash step
CREATE TABLE receta.lavado_maquina_paso_insumo (
    id       INT           GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    paso_id  INT           NOT NULL REFERENCES receta.lavado_maquina_paso(id) ON DELETE CASCADE,
    item_id  INT           NOT NULL REFERENCES item(id),
    cantidad NUMERIC(8,4)  NOT NULL,
    orden    SMALLINT      NOT NULL,
    UNIQUE(paso_id, orden)
);

-- ───────────────────────────────────────
-- GRANTS
-- ───────────────────────────────────────

GRANT SELECT ON estado_desarrollo_color           TO authenticated;
GRANT USAGE ON SCHEMA receta TO authenticated;
GRANT SELECT ON receta.operacion                  TO authenticated;
GRANT SELECT ON receta.tenido                     TO authenticated;
GRANT SELECT ON receta.tenido_paso                TO authenticated;
GRANT SELECT ON receta.tenido_paso_insumo         TO authenticated;
GRANT SELECT ON receta.lavado_maquina             TO authenticated;
GRANT SELECT ON receta.lavado_maquina_paso        TO authenticated;
GRANT SELECT ON receta.lavado_maquina_paso_insumo TO authenticated;


-- ═══════════════════════════════════════════════════════════════
-- NOTE: public.desarrollo_color REMOVED
-- Was never populated. Recipe development lifecycle is now tracked
-- via receta.tenido.estado_id (EN_DESARROLLO → APROBADO → HISTORICO).
-- ═══════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════
-- MIGRATION (dev env)
-- Run these against the existing DB to sync with the DDL above.
-- Assumes GENERATED BY DEFAULT AS IDENTITY — use OVERRIDING SYSTEM VALUE for id inserts.
-- ═══════════════════════════════════════════════════════════════

-- Step 1: Create schema
-- CREATE SCHEMA IF NOT EXISTS receta;

-- Step 2: Move and rename legacy headers (data preserved automatically)
-- ALTER TABLE public.receta2              SET SCHEMA receta;
-- ALTER TABLE receta.receta2              RENAME TO tenido;
-- ALTER TABLE public.receta_lavado_maquina SET SCHEMA receta;
-- ALTER TABLE receta.receta_lavado_maquina RENAME TO lavado_maquina;

-- Step 3: Create receta.operacion and seed (if receta_operacion exists in public, migrate instead):
-- INSERT INTO receta.operacion OVERRIDING SYSTEM VALUE
--     SELECT id, codigo, codigo_canon, nombre FROM public.receta_operacion;

-- Step 4: Move and rename child tables, update FK column names
-- ALTER TABLE public.receta_paso SET SCHEMA receta;
-- ALTER TABLE receta.receta_paso RENAME TO tenido_paso;
-- ALTER TABLE receta.tenido_paso
--     RENAME COLUMN receta_operacion_id TO operacion_id;
-- -- Update FK: receta_id still targets receta.tenido (same OID, schema moved) — no action needed

-- ALTER TABLE public.receta_paso_insumo SET SCHEMA receta;
-- ALTER TABLE receta.receta_paso_insumo RENAME TO tenido_paso_insumo;
-- ALTER TABLE receta.tenido_paso_insumo
--     RENAME COLUMN receta_paso_id TO paso_id;

-- ALTER TABLE public.receta_lavado_maquina_paso SET SCHEMA receta;
-- ALTER TABLE receta.receta_lavado_maquina_paso RENAME TO lavado_maquina_paso;
-- ALTER TABLE receta.lavado_maquina_paso
--     RENAME COLUMN receta_lavado_maquina_id TO receta_id;
-- ALTER TABLE receta.lavado_maquina_paso
--     RENAME COLUMN receta_operacion_id TO operacion_id;

-- ALTER TABLE public.receta_lavado_maquina_paso_insumo SET SCHEMA receta;
-- ALTER TABLE receta.receta_lavado_maquina_paso_insumo RENAME TO lavado_maquina_paso_insumo;
-- ALTER TABLE receta.lavado_maquina_paso_insumo
--     RENAME COLUMN receta_lavado_maquina_paso_id TO paso_id;

-- Step 5: Update FK references in mes schema
-- ALTER TABLE mes.orden_produccion_paso
--     DROP CONSTRAINT IF EXISTS orden_produccion_paso_receta_id_fkey,
--     ADD  CONSTRAINT orden_produccion_paso_receta_id_fkey
--         FOREIGN KEY (receta_id) REFERENCES receta.tenido(id);

-- ALTER TABLE mes.lavado_maquina
--     RENAME COLUMN receta_lavado_maquina_id TO receta_id;
-- ALTER TABLE mes.lavado_maquina
--     DROP CONSTRAINT IF EXISTS mes_lavado_maquina_receta_lavado_maquina_id_fkey,
--     ADD  CONSTRAINT mes_lavado_maquina_receta_id_fkey
--         FOREIGN KEY (receta_id) REFERENCES receta.lavado_maquina(id);

-- Step 6: Drop legacy flat tables (after verifying all data migrated)
-- DROP TABLE IF EXISTS public.receta_lavado_maquina_x_insumo;
-- DROP TABLE IF EXISTS public.receta_lavado_maquina_x_paso;
-- DROP TABLE IF EXISTS public.receta_x_insumo;
-- DROP TABLE IF EXISTS public.receta_x_paso;
-- DROP TABLE IF EXISTS public.receta_operacion;  -- only after receta.operacion is populated

-- ─────────────────────────────────────────────────────────────
-- Step 7: Normalize receta.tenido (run after tablas.sql rename migrations)
-- ─────────────────────────────────────────────────────────────

-- 7 prerequisite: Add codigo column to estado_desarrollo_color and seed HISTORICO
-- (table exists in DB but has no codigo column — needed by trigger and migration)
-- ALTER TABLE estado_desarrollo_color ADD COLUMN IF NOT EXISTS codigo TEXT;
-- UPDATE estado_desarrollo_color SET codigo = CASE nombre
--     WHEN 'Ingresado'          THEN 'INGRESADO'
--     WHEN 'En Desarrollo'      THEN 'EN_DESARROLLO'
--     WHEN 'Enviado al Cliente' THEN 'ENVIADO_CLIENTE'
--     WHEN 'Aprobado'           THEN 'APROBADO'
--     WHEN 'Rechazado'          THEN 'RECHAZADO'
--     WHEN 'Cancelado'          THEN 'CANCELADO'
--     WHEN 'Re Lab'             THEN 'RE_LAB'
-- END;
-- ALTER TABLE estado_desarrollo_color ALTER COLUMN codigo SET NOT NULL;
-- CREATE UNIQUE INDEX IF NOT EXISTS uq_edc_codigo ON estado_desarrollo_color(codigo);
-- INSERT INTO estado_desarrollo_color (nombre, codigo) VALUES ('Histórico', 'HISTORICO');

-- 7a: Replace tipo_articulo_id + fibra with articulo_id
-- ALTER TABLE receta.tenido ADD COLUMN articulo_id INT REFERENCES articulo(id);
-- UPDATE receta.tenido rt SET articulo_id = ar.id
--     FROM articulo ar
--     WHERE ar.articulo_tipo_id = rt.tipo_articulo_id
--       AND ar.fibra = rt.fibra;
-- ALTER TABLE receta.tenido DROP COLUMN tipo_articulo_id;
-- ALTER TABLE receta.tenido DROP COLUMN fibra;

-- 7b: Add estado_id, backfill from dual-boolean, drop flg_activo
--     (flg_produccion is KEPT — semantics change to trigger-maintained)
-- ALTER TABLE receta.tenido ADD COLUMN estado_id SMALLINT REFERENCES estado_desarrollo_color(id);
-- UPDATE receta.tenido SET estado_id = (SELECT id FROM estado_desarrollo_color WHERE codigo = 'APROBADO')
--     WHERE flg_produccion = true;
-- UPDATE receta.tenido SET estado_id = (SELECT id FROM estado_desarrollo_color WHERE codigo = 'EN_DESARROLLO')
--     WHERE flg_produccion = false AND flg_activo = true;
-- UPDATE receta.tenido SET estado_id = (SELECT id FROM estado_desarrollo_color WHERE codigo = 'CANCELADO')
--     WHERE estado_id IS NULL;
-- ALTER TABLE receta.tenido ALTER COLUMN estado_id SET NOT NULL;
-- ALTER TABLE receta.tenido DROP COLUMN flg_activo;

-- 7c: Create trigger, backfill flg_produccion, add partial unique index
-- (HISTORICO already inserted in step 7 prerequisite above)
-- CREATE OR REPLACE FUNCTION fn_trg_receta_tenido_flg_produccion() ... (paste from DDL above);
-- CREATE TRIGGER trg_bi_receta_tenido_flg_produccion ... (paste from DDL above);
-- UPDATE receta.tenido SET flg_produccion = (
--     estado_id = (SELECT id FROM estado_desarrollo_color WHERE codigo = 'APROBADO')
-- );
-- CREATE UNIQUE INDEX uq_receta_tenido_aprobada
--     ON receta.tenido(color_x_cliente_id, articulo_id, tenido_id, flg_antipilling)
--     WHERE flg_produccion = true;

-- 7d: Drop desarrollo_color (was never populated — safe to drop)
-- DROP TABLE IF EXISTS public.desarrollo_color;
