-- ═══════════════════════════════════════════════════════════════
-- receta SCHEMA — recipe master data (process engineering domain)
--
-- Domain split:
--   receta.tenido         → dyeing recipe formula
--   receta.lavado_maquina → machine wash recipe formula
--   receta.operacion      → chemistry step catalog
--
-- NOTE: receta.operacion  = micro-level chemistry steps within a recipe
--       mes.operacion     = macro-level production operations (TENIDO, SECADO…)
--       Same name, different granularity, different schema, never JOINed together.
--
-- Consumers:
--   mes.orden_produccion_paso.receta_id    → receta.tenido(id)
--   mes.lavado_maquina.receta_id           → receta.lavado_maquina(id)
-- ═══════════════════════════════════════════════════════════════

CREATE SCHEMA IF NOT EXISTS receta;

-- ───────────────────────────────────────
-- Chemistry operation catalog
-- ───────────────────────────────────────

CREATE TABLE receta.operacion (
    id           SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo       TEXT NOT NULL UNIQUE,
    codigo_canon TEXT NOT NULL UNIQUE,
    nombre       TEXT NOT NULL
);

CREATE TRIGGER trg_bi_receta_operacion_codigo_canon
BEFORE INSERT OR UPDATE ON receta.operacion
FOR EACH ROW
EXECUTE FUNCTION fn_trg_set_codigo_canon();

INSERT INTO receta.operacion (codigo, nombre) VALUES
    ('TINTURA',           'Tintura'),
    ('LAVADO',            'Lavado'),
    ('LAVADO_REDUCTIVO',  'Lavado Reductivo'),
    ('BLANQUEO_QUIMICO',  'Blanqueo Químico'),
    ('BLANQUEO_OPTICO',   'Blanqueo Óptico'),
    ('DESCRUDE',          'Descrude'),
    ('NEUTRALIZADO',      'Neutralizado'),
    ('SUAVIZADO',         'Suavizado'),
    ('FIJADO',            'Fijado'),
    ('JABONADO',          'Jabonado'),
    ('ENJUAGUE',          'Enjuague'),
    ('MATIZADO',          'Matizado'),
    ('ANTIPILLING',       'Antipilling'),
    ('REGULACION_PH',     'Regulación de pH'),
    ('SIMULTANEO',        'Simultáneo'),
    ('DESMONTADO',        'Desmontado'),
    ('REBAJE',            'Rebaje');

-- ───────────────────────────────────────
-- Dyeing recipe header
-- (migrated from public.receta2)
-- ───────────────────────────────────────

CREATE TABLE receta.tenido (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color_x_cliente_id INT     REFERENCES color_x_cliente(id),
    tipo_articulo_id   INT     REFERENCES tipo_articulo(id),
    tenido_id          INT     REFERENCES tenido(id),
    fibra              SMALLINT,
    tipo_receta_id     SMALLINT REFERENCES tipo_receta(id),
    flg_activo         BOOLEAN  DEFAULT true,
    flg_antipilling    BOOLEAN  DEFAULT false,
    flg_produccion     BOOLEAN  DEFAULT false,
    fyh_produccion     TIMESTAMPTZ,
    usr_cre            INT      REFERENCES profiles(id_usuario),
    fyh_cre            TIMESTAMPTZ DEFAULT now(),
    usr_mod            INT      REFERENCES profiles(id_usuario),
    fyh_mod            TIMESTAMPTZ
);

-- Dyeing recipe steps (ordered chemistry sequence within the recipe)
CREATE TABLE receta.tenido_paso (
    id           INT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_id    INT      NOT NULL REFERENCES receta.tenido(id),
    operacion_id SMALLINT NOT NULL REFERENCES receta.operacion(id),
    orden        SMALLINT NOT NULL,
    ph           NUMERIC(4,2),
    temperatura  NUMERIC(5,2),
    tiempo_min   SMALLINT,
    nota         TEXT,
    UNIQUE(receta_id, orden)
);

-- Chemicals per dyeing step
CREATE TABLE receta.tenido_paso_insumo (
    id       INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    paso_id  INT             NOT NULL REFERENCES receta.tenido_paso(id) ON DELETE CASCADE,
    item_id  INT             NOT NULL REFERENCES item(id),
    cantidad NUMERIC(8,4)   NOT NULL,
    orden    SMALLINT        NOT NULL,
    UNIQUE(paso_id, orden)
);

-- ───────────────────────────────────────
-- Machine wash recipe header
-- (migrated from public.receta_lavado_maquina)
-- ───────────────────────────────────────

CREATE TABLE receta.lavado_maquina (
    id                INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_lavado_mq_id SMALLINT REFERENCES tipo_lavado_maquina(id),
    valor_origen_id   SMALLINT REFERENCES valor(id),
    valor_destino_id  SMALLINT REFERENCES valor(id),
    flg_activo        BOOLEAN  DEFAULT true,
    usr_cre           INT      REFERENCES profiles(id_usuario),
    fyh_cre           TIMESTAMPTZ DEFAULT now(),
    usr_mod           INT      REFERENCES profiles(id_usuario),
    fyh_mod           TIMESTAMPTZ
);

-- Wash recipe steps
CREATE TABLE receta.lavado_maquina_paso (
    id           INT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receta_id    INT      NOT NULL REFERENCES receta.lavado_maquina(id),
    operacion_id SMALLINT NOT NULL REFERENCES receta.operacion(id),
    orden        SMALLINT NOT NULL,
    ph           NUMERIC(4,2),
    temperatura  NUMERIC(5,2),
    tiempo_min   SMALLINT,
    nota         TEXT,
    UNIQUE(receta_id, orden)
);

-- Chemicals per wash step
CREATE TABLE receta.lavado_maquina_paso_insumo (
    id       INT           GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    paso_id  INT           NOT NULL REFERENCES receta.lavado_maquina_paso(id) ON DELETE CASCADE,
    item_id  INT           NOT NULL REFERENCES item(id),
    cantidad NUMERIC(8,4)  NOT NULL,
    orden    SMALLINT      NOT NULL,
    UNIQUE(paso_id, orden)
);

-- ───────────────────────────────────────
-- GRANTS
-- ───────────────────────────────────────

GRANT USAGE ON SCHEMA receta TO authenticated;
GRANT SELECT ON receta.operacion                  TO authenticated;
GRANT SELECT ON receta.tenido                     TO authenticated;
GRANT SELECT ON receta.tenido_paso                TO authenticated;
GRANT SELECT ON receta.tenido_paso_insumo         TO authenticated;
GRANT SELECT ON receta.lavado_maquina             TO authenticated;
GRANT SELECT ON receta.lavado_maquina_paso        TO authenticated;
GRANT SELECT ON receta.lavado_maquina_paso_insumo TO authenticated;


-- ═══════════════════════════════════════════════════════════════
-- COLOR DEVELOPMENT (separate domain)
-- TODO: evaluate denormalizing into receta.tenido header
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.desarrollo_color
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    color_x_cliente_id smallint,
    tipo_articulo_id smallint,
    tenido_id smallint,
    fecha_ingreso date NOT NULL,
    estado_desarrollo_color_id smallint,
    fecha_estado_actual date,
    descripcion text COLLATE pg_catalog."default",
    fyh_cre timestamp without time zone DEFAULT now(),
    fyh_cre_tz timestamp with time zone DEFAULT now(),
    CONSTRAINT desarrollo_color_pkey PRIMARY KEY (id),
    CONSTRAINT uq_desarrollo UNIQUE (color_x_cliente_id, tipo_articulo_id, tenido_id),
    CONSTRAINT desarrollo_color_fk_color_x_cliente_fkey FOREIGN KEY (color_x_cliente_id)
        REFERENCES public.color_x_cliente (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT desarrollo_color_fk_estado_desarrollo_color_fkey FOREIGN KEY (estado_desarrollo_color_id)
        REFERENCES public.estado_desarrollo_color (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT desarrollo_color_fk_tenido_fkey FOREIGN KEY (tenido_id)
        REFERENCES public.tenido (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT desarrollo_color_fk_tipo_articulo_fkey FOREIGN KEY (tipo_articulo_id)
        REFERENCES public.tipo_articulo (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);


-- ═══════════════════════════════════════════════════════════════
-- MIGRATION (dev env)
-- Run these against the existing DB to sync with the DDL above.
-- Assumes GENERATED BY DEFAULT AS IDENTITY — use OVERRIDING SYSTEM VALUE for id inserts.
-- ═══════════════════════════════════════════════════════════════

-- Step 1: Create schema
-- CREATE SCHEMA IF NOT EXISTS receta;

-- Step 2: Move and rename legacy headers (data preserved automatically)
-- ALTER TABLE public.receta2              SET SCHEMA receta;
-- ALTER TABLE receta.receta2              RENAME TO tenido;
-- ALTER TABLE public.receta_lavado_maquina SET SCHEMA receta;
-- ALTER TABLE receta.receta_lavado_maquina RENAME TO lavado_maquina;

-- Step 3: Create receta.operacion and seed (if receta_operacion exists in public, migrate instead):
-- INSERT INTO receta.operacion OVERRIDING SYSTEM VALUE
--     SELECT id, codigo, codigo_canon, nombre FROM public.receta_operacion;

-- Step 4: Move and rename child tables, update FK column names
-- ALTER TABLE public.receta_paso SET SCHEMA receta;
-- ALTER TABLE receta.receta_paso RENAME TO tenido_paso;
-- ALTER TABLE receta.tenido_paso
--     RENAME COLUMN receta_operacion_id TO operacion_id;
-- -- Update FK: receta_id still targets receta.tenido (same OID, schema moved) — no action needed

-- ALTER TABLE public.receta_paso_insumo SET SCHEMA receta;
-- ALTER TABLE receta.receta_paso_insumo RENAME TO tenido_paso_insumo;
-- ALTER TABLE receta.tenido_paso_insumo
--     RENAME COLUMN receta_paso_id TO paso_id;

-- ALTER TABLE public.receta_lavado_maquina_paso SET SCHEMA receta;
-- ALTER TABLE receta.receta_lavado_maquina_paso RENAME TO lavado_maquina_paso;
-- ALTER TABLE receta.lavado_maquina_paso
--     RENAME COLUMN receta_lavado_maquina_id TO receta_id;
-- ALTER TABLE receta.lavado_maquina_paso
--     RENAME COLUMN receta_operacion_id TO operacion_id;

-- ALTER TABLE public.receta_lavado_maquina_paso_insumo SET SCHEMA receta;
-- ALTER TABLE receta.receta_lavado_maquina_paso_insumo RENAME TO lavado_maquina_paso_insumo;
-- ALTER TABLE receta.lavado_maquina_paso_insumo
--     RENAME COLUMN receta_lavado_maquina_paso_id TO paso_id;

-- Step 5: Update FK references in mes schema
-- ALTER TABLE mes.orden_produccion_paso
--     DROP CONSTRAINT IF EXISTS orden_produccion_paso_receta_id_fkey,
--     ADD  CONSTRAINT orden_produccion_paso_receta_id_fkey
--         FOREIGN KEY (receta_id) REFERENCES receta.tenido(id);

-- ALTER TABLE mes.lavado_maquina
--     RENAME COLUMN receta_lavado_maquina_id TO receta_id;
-- ALTER TABLE mes.lavado_maquina
--     DROP CONSTRAINT IF EXISTS mes_lavado_maquina_receta_lavado_maquina_id_fkey,
--     ADD  CONSTRAINT mes_lavado_maquina_receta_id_fkey
--         FOREIGN KEY (receta_id) REFERENCES receta.lavado_maquina(id);

-- Step 6: Drop legacy flat tables (after verifying all data migrated)
-- DROP TABLE IF EXISTS public.receta_lavado_maquina_x_insumo;
-- DROP TABLE IF EXISTS public.receta_lavado_maquina_x_paso;
-- DROP TABLE IF EXISTS public.receta_x_insumo;
-- DROP TABLE IF EXISTS public.receta_x_paso;
-- DROP TABLE IF EXISTS public.receta_operacion;  -- only after receta.operacion is populated
